import Foundation

nonisolated struct LocalizationService: Sendable {
    static func translate(_ key: String, language: String) -> String {
        if language == "English" { return key }
        guard let langDict = translations[language],
              let translated = langDict[key] else {
            return key
        }
        return translated
    }

    static let translations: [String: [String: String]] = [
        "Spanish": [
            "Transform Your": "Transforma Tu",
            "Physique with AI": "Físico con IA",
            "Your personal AI fitness coach.\nScan, plan, and compete.": "Tu entrenador personal de IA.\nEscanea, planifica y compite.",
            "Get Started": "Comenzar",
            "Existing user? Log in": "¿Ya tienes cuenta? Inicia sesión",
            "By continuing you agree to our": "Al continuar aceptas nuestros",
            "Terms": "Términos",
            "and": "y",
            "Privacy Policy": "Política de Privacidad",
            "Choose Your Language": "Elige Tu Idioma",
            "Continue": "Continuar",
            "What's your": "¿Cuál es tu",
            "gender?": "género?",
            "Male": "Masculino",
            "Female": "Femenino",
            "How many times": "¿Cuántas veces",
            "per week?": "por semana?",
            "How often do you want to train": "¿Con qué frecuencia quieres entrenar?",
            "Just starting": "Empezando",
            "Casual": "Casual",
            "Moderate": "Moderado",
            "Dedicated": "Dedicado",
            "Intense": "Intenso",
            "Athlete": "Atleta",
            "Every day": "Todos los días",
            "Training": "Entrenamiento",
            "Experience": "Experiencia",
            "How long have you been training?": "¿Cuánto tiempo llevas entrenando?",
            "Beginner": "Principiante",
            "Less than 6 months": "Menos de 6 meses",
            "Intermediate": "Intermedio",
            "6 months – 2 years": "6 meses – 2 años",
            "Advanced": "Avanzado",
            "2+ years of training": "Más de 2 años entrenando",
            "Expert": "Experto",
            "Competitive level": "Nivel competitivo",
            "Where do": "¿Dónde",
            "you train?": "entrenas?",
            "Gym": "Gimnasio",
            "Full equipment access": "Acceso completo al equipo",
            "Home": "Casa",
            "Bodyweight & minimal gear": "Peso corporal y equipo mínimo",
            "Both": "Ambos",
            "Mix of gym and home": "Mezcla de gimnasio y casa",
            "Available equipment": "Equipo disponible",
            "Dumbbells": "Mancuernas",
            "Pull-up Bar": "Barra de dominadas",
            "Bodyweight Only": "Solo peso corporal",
            "Primary": "Objetivo",
            "Goal": "Principal",
            "What's your #1 focus right now?": "¿Cuál es tu enfoque #1 ahora?",
            "Build Muscle": "Ganar Músculo",
            "Gain size and strength": "Ganar tamaño y fuerza",
            "Lose Fat": "Perder Grasa",
            "Lean down and cut body fat": "Adelgazar y reducir grasa",
            "Recomp": "Recomposición",
            "Build muscle while losing fat": "Ganar músculo mientras pierdes grasa",
            "Your Body": "Tu Cuerpo",
            "Measurements": "Medidas",
            "Imperial": "Imperial",
            "Metric": "Métrico",
            "HEIGHT": "ALTURA",
            "WEIGHT": "PESO",
            "What's holding": "¿Qué te",
            "you back?": "detiene?",
            "Select all that apply": "Selecciona todo lo que aplique",
            "Lack of motivation": "Falta de motivación",
            "No workout plan": "Sin plan de entrenamiento",
            "Poor nutrition": "Mala nutrición",
            "Inconsistency": "Inconsistencia",
            "Time management": "Gestión del tiempo",
            "Injuries or pain": "Lesiones o dolor",
            "Low energy": "Baja energía",
            "Not seeing results": "Sin ver resultados",
            "Gym intimidation": "Intimidación en el gym",
            "Don't know where to start": "No sé por dónde empezar",
            "In 90 days,": "En 90 días,",
            "I want to...": "Quiero...",
            "Choose your top goals": "Elige tus metas principales",
            "Build muscle": "Ganar músculo",
            "Lose fat": "Perder grasa",
            "Get stronger": "Ser más fuerte",
            "Improve endurance": "Mejorar resistencia",
            "Better posture": "Mejor postura",
            "Increase flexibility": "Aumentar flexibilidad",
            "Run a marathon": "Correr un maratón",
            "Feel more confident": "Sentirme más seguro",
            "Build a routine": "Crear una rutina",
            "Compete in fitness": "Competir en fitness",
            "Confidence": "Confianza",
            "How experienced are you?": "¿Qué tan experimentado eres?",
            "Just getting started": "Recién empezando",
            "Know the basics well": "Conozco bien lo básico",
            "Years of experience": "Años de experiencia",
            "Competitive athlete level": "Nivel de atleta competitivo",
            "Referral Code": "Código de Referencia",
            "Got a code from a friend?": "¿Tienes un código de un amigo?",
            "Enter code": "Ingresa el código",
            "Apply & Continue": "Aplicar y Continuar",
            "I don't have a code": "No tengo un código",
            "Create Your Account": "Crea Tu Cuenta",
            "Sign up to save your progress": "Regístrate para guardar tu progreso",
            "Continue with Google": "Continuar con Google",
            "Continue with Email": "Continuar con Email",
            "Scan": "Escanear",
            "Plan": "Plan",
            "Compete": "Competir",
            "Profile": "Perfil",
            "Settings": "Ajustes",
            "Notifications": "Notificaciones",
            "Dark Mode": "Modo Oscuro",
            "Apple Health": "Apple Health",
            "Restore Purchases": "Restaurar Compras",
            "Terms & Privacy": "Términos y Privacidad",
            "Log Out": "Cerrar Sesión",
            "Scan History": "Historial de Escaneos",
            "No scans yet": "Sin escaneos aún",
            "Limited Offer": "Oferta Limitada",
            "off Pro — Claim now": "de descuento Pro — Reclama ahora",
            "Edit Profile": "Editar Perfil",
            "Cancel": "Cancelar",
            "Save": "Guardar",
            "Remove Photo": "Eliminar Foto",
            "Name": "Nombre",
            "Short bio (optional)": "Bio corta (opcional)",
            "Language": "Idioma",
            "Scans": "Escaneos",
            "Workouts": "Entrenamientos",
            "Streak": "Racha"
        ],
        "French": [
            "Transform Your": "Transformez Votre",
            "Physique with AI": "Physique avec l'IA",
            "Your personal AI fitness coach.\nScan, plan, and compete.": "Votre coach fitness IA personnel.\nScannez, planifiez et compétez.",
            "Get Started": "Commencer",
            "Existing user? Log in": "Déjà inscrit ? Connectez-vous",
            "By continuing you agree to our": "En continuant vous acceptez nos",
            "Terms": "Conditions",
            "and": "et",
            "Privacy Policy": "Politique de Confidentialité",
            "Choose Your Language": "Choisissez Votre Langue",
            "Continue": "Continuer",
            "What's your": "Quel est votre",
            "gender?": "genre ?",
            "Male": "Homme",
            "Female": "Femme",
            "How many times": "Combien de fois",
            "per week?": "par semaine ?",
            "How often do you want to train": "À quelle fréquence voulez-vous vous entraîner ?",
            "Just starting": "Débutant",
            "Casual": "Occasionnel",
            "Moderate": "Modéré",
            "Dedicated": "Dédié",
            "Intense": "Intense",
            "Athlete": "Athlète",
            "Every day": "Tous les jours",
            "Training": "Entraînement",
            "Experience": "Expérience",
            "How long have you been training?": "Depuis combien de temps vous entraînez-vous ?",
            "Beginner": "Débutant",
            "Less than 6 months": "Moins de 6 mois",
            "Intermediate": "Intermédiaire",
            "6 months – 2 years": "6 mois – 2 ans",
            "Advanced": "Avancé",
            "2+ years of training": "Plus de 2 ans d'entraînement",
            "Expert": "Expert",
            "Competitive level": "Niveau compétitif",
            "Where do": "Où",
            "you train?": "vous entraînez-vous ?",
            "Gym": "Salle de sport",
            "Full equipment access": "Accès complet aux équipements",
            "Home": "Maison",
            "Bodyweight & minimal gear": "Poids du corps et équipement minimal",
            "Both": "Les deux",
            "Mix of gym and home": "Mélange salle et maison",
            "Available equipment": "Équipement disponible",
            "Dumbbells": "Haltères",
            "Pull-up Bar": "Barre de traction",
            "Bodyweight Only": "Poids du corps seul",
            "Primary": "Objectif",
            "Goal": "Principal",
            "What's your #1 focus right now?": "Quel est votre objectif #1 maintenant ?",
            "Build Muscle": "Prendre du Muscle",
            "Gain size and strength": "Gagner en taille et en force",
            "Lose Fat": "Perdre du Gras",
            "Lean down and cut body fat": "Maigrir et réduire la graisse",
            "Recomp": "Recomposition",
            "Build muscle while losing fat": "Prendre du muscle en perdant du gras",
            "Your Body": "Votre Corps",
            "Measurements": "Mensurations",
            "Imperial": "Impérial",
            "Metric": "Métrique",
            "HEIGHT": "TAILLE",
            "WEIGHT": "POIDS",
            "What's holding": "Qu'est-ce qui",
            "you back?": "vous freine ?",
            "Select all that apply": "Sélectionnez tout ce qui s'applique",
            "Lack of motivation": "Manque de motivation",
            "No workout plan": "Pas de programme",
            "Poor nutrition": "Mauvaise nutrition",
            "Inconsistency": "Inconstance",
            "Time management": "Gestion du temps",
            "Injuries or pain": "Blessures ou douleur",
            "Low energy": "Manque d'énergie",
            "Not seeing results": "Pas de résultats visibles",
            "Gym intimidation": "Intimidation à la salle",
            "Don't know where to start": "Ne sais pas par où commencer",
            "In 90 days,": "En 90 jours,",
            "I want to...": "Je veux...",
            "Choose your top goals": "Choisissez vos objectifs principaux",
            "Build muscle": "Prendre du muscle",
            "Lose fat": "Perdre du gras",
            "Get stronger": "Devenir plus fort",
            "Improve endurance": "Améliorer l'endurance",
            "Better posture": "Meilleure posture",
            "Increase flexibility": "Augmenter la flexibilité",
            "Run a marathon": "Courir un marathon",
            "Feel more confident": "Se sentir plus confiant",
            "Build a routine": "Créer une routine",
            "Compete in fitness": "Compétition fitness",
            "Confidence": "Confiance",
            "How experienced are you?": "Quel est votre niveau ?",
            "Just getting started": "Tout juste débutant",
            "Know the basics well": "Bonne maîtrise des bases",
            "Years of experience": "Années d'expérience",
            "Competitive athlete level": "Niveau athlète compétitif",
            "Referral Code": "Code de Parrainage",
            "Got a code from a friend?": "Vous avez un code d'un ami ?",
            "Enter code": "Entrez le code",
            "Apply & Continue": "Appliquer et Continuer",
            "I don't have a code": "Je n'ai pas de code",
            "Create Your Account": "Créez Votre Compte",
            "Sign up to save your progress": "Inscrivez-vous pour sauvegarder",
            "Continue with Google": "Continuer avec Google",
            "Continue with Email": "Continuer avec Email",
            "Scan": "Scanner",
            "Plan": "Plan",
            "Compete": "Compétition",
            "Profile": "Profil",
            "Settings": "Paramètres",
            "Notifications": "Notifications",
            "Dark Mode": "Mode Sombre",
            "Apple Health": "Apple Health",
            "Restore Purchases": "Restaurer les Achats",
            "Terms & Privacy": "Conditions et Confidentialité",
            "Log Out": "Déconnexion",
            "Scan History": "Historique des Scans",
            "No scans yet": "Aucun scan",
            "Limited Offer": "Offre Limitée",
            "off Pro — Claim now": "de réduction Pro — Réclamez",
            "Edit Profile": "Modifier le Profil",
            "Cancel": "Annuler",
            "Save": "Enregistrer",
            "Remove Photo": "Supprimer la Photo",
            "Name": "Nom",
            "Short bio (optional)": "Bio courte (optionnel)",
            "Language": "Langue",
            "Scans": "Scans",
            "Workouts": "Entraînements",
            "Streak": "Série"
        ],
        "German": [
            "Transform Your": "Verwandle Dein",
            "Physique with AI": "Physique mit KI",
            "Your personal AI fitness coach.\nScan, plan, and compete.": "Dein persönlicher KI-Fitness-Coach.\nScannen, planen und wettkämpfen.",
            "Get Started": "Loslegen",
            "Existing user? Log in": "Bereits registriert? Anmelden",
            "Continue": "Weiter",
            "What's your": "Was ist dein",
            "gender?": "Geschlecht?",
            "Male": "Männlich",
            "Female": "Weiblich",
            "How many times": "Wie oft",
            "per week?": "pro Woche?",
            "How often do you want to train": "Wie oft möchtest du trainieren?",
            "Training": "Training",
            "Experience": "Erfahrung",
            "How long have you been training?": "Wie lange trainierst du schon?",
            "Beginner": "Anfänger",
            "Less than 6 months": "Weniger als 6 Monate",
            "Intermediate": "Fortgeschritten",
            "6 months – 2 years": "6 Monate – 2 Jahre",
            "Advanced": "Erfahren",
            "2+ years of training": "2+ Jahre Training",
            "Expert": "Experte",
            "Competitive level": "Wettkampfniveau",
            "Where do": "Wo",
            "you train?": "trainierst du?",
            "Gym": "Fitnessstudio",
            "Full equipment access": "Voller Gerätezugang",
            "Home": "Zuhause",
            "Bodyweight & minimal gear": "Körpergewicht & minimale Geräte",
            "Both": "Beides",
            "Mix of gym and home": "Mix aus Studio und Zuhause",
            "Available equipment": "Verfügbare Geräte",
            "Dumbbells": "Hanteln",
            "Pull-up Bar": "Klimmzugstange",
            "Bodyweight Only": "Nur Körpergewicht",
            "Primary": "Primäres",
            "Goal": "Ziel",
            "What's your #1 focus right now?": "Was ist dein #1 Fokus?",
            "Build Muscle": "Muskeln aufbauen",
            "Gain size and strength": "Masse und Kraft aufbauen",
            "Lose Fat": "Fett verlieren",
            "Lean down and cut body fat": "Abnehmen und Fett reduzieren",
            "Recomp": "Rekomposition",
            "Build muscle while losing fat": "Muskeln aufbauen und Fett verlieren",
            "Your Body": "Dein Körper",
            "Measurements": "Maße",
            "Imperial": "Imperial",
            "Metric": "Metrisch",
            "HEIGHT": "GRÖSSE",
            "WEIGHT": "GEWICHT",
            "What's holding": "Was hält",
            "you back?": "dich zurück?",
            "Select all that apply": "Alles Zutreffende auswählen",
            "In 90 days,": "In 90 Tagen,",
            "I want to...": "Ich möchte...",
            "Choose your top goals": "Wähle deine Top-Ziele",
            "Confidence": "Selbstvertrauen",
            "How experienced are you?": "Wie erfahren bist du?",
            "Just getting started": "Gerade erst angefangen",
            "Know the basics well": "Grundlagen gut bekannt",
            "Years of experience": "Jahre an Erfahrung",
            "Competitive athlete level": "Wettkampfathletenniveau",
            "Referral Code": "Empfehlungscode",
            "Got a code from a friend?": "Code von einem Freund?",
            "Enter code": "Code eingeben",
            "Apply & Continue": "Anwenden & Weiter",
            "I don't have a code": "Ich habe keinen Code",
            "Create Your Account": "Erstelle Dein Konto",
            "Sign up to save your progress": "Registriere dich um Fortschritt zu speichern",
            "Continue with Google": "Weiter mit Google",
            "Continue with Email": "Weiter mit E-Mail",
            "Scan": "Scannen",
            "Plan": "Plan",
            "Compete": "Wettkampf",
            "Profile": "Profil",
            "Settings": "Einstellungen",
            "Notifications": "Benachrichtigungen",
            "Dark Mode": "Dunkelmodus",
            "Apple Health": "Apple Health",
            "Restore Purchases": "Käufe wiederherstellen",
            "Terms & Privacy": "AGB & Datenschutz",
            "Log Out": "Abmelden",
            "Scan History": "Scan-Verlauf",
            "No scans yet": "Noch keine Scans",
            "Limited Offer": "Begrenztes Angebot",
            "off Pro — Claim now": "Rabatt Pro — Jetzt sichern",
            "Edit Profile": "Profil bearbeiten",
            "Cancel": "Abbrechen",
            "Save": "Speichern",
            "Remove Photo": "Foto entfernen",
            "Name": "Name",
            "Short bio (optional)": "Kurze Bio (optional)",
            "Language": "Sprache",
            "Scans": "Scans",
            "Workouts": "Trainings",
            "Streak": "Serie",
            "Just starting": "Erst anfangend",
            "Casual": "Gelegentlich",
            "Moderate": "Moderat",
            "Dedicated": "Engagiert",
            "Intense": "Intensiv",
            "Athlete": "Athlet",
            "Every day": "Jeden Tag",
            "Lack of motivation": "Mangelnde Motivation",
            "No workout plan": "Kein Trainingsplan",
            "Poor nutrition": "Schlechte Ernährung",
            "Inconsistency": "Inkonsequenz",
            "Time management": "Zeitmanagement",
            "Injuries or pain": "Verletzungen oder Schmerzen",
            "Low energy": "Wenig Energie",
            "Not seeing results": "Keine Ergebnisse sehen",
            "Gym intimidation": "Einschüchterung im Gym",
            "Don't know where to start": "Weiß nicht wo anfangen",
            "Build muscle": "Muskeln aufbauen",
            "Lose fat": "Fett verlieren",
            "Get stronger": "Stärker werden",
            "Improve endurance": "Ausdauer verbessern",
            "Better posture": "Bessere Haltung",
            "Increase flexibility": "Flexibilität steigern",
            "Run a marathon": "Marathon laufen",
            "Feel more confident": "Selbstbewusster fühlen",
            "Build a routine": "Routine aufbauen",
            "Compete in fitness": "Im Fitness wettkämpfen",
            "Choose Your Language": "Wähle Deine Sprache",
            "Terms": "AGB",
            "and": "und",
            "Privacy Policy": "Datenschutz",
            "By continuing you agree to our": "Durch Fortfahren stimmst du zu"
        ],
        "Portuguese": [
            "Transform Your": "Transforme Seu",
            "Physique with AI": "Físico com IA",
            "Get Started": "Começar",
            "Existing user? Log in": "Já tem conta? Entrar",
            "Continue": "Continuar",
            "What's your": "Qual é o seu",
            "gender?": "gênero?",
            "Male": "Masculino",
            "Female": "Feminino",
            "How many times": "Quantas vezes",
            "per week?": "por semana?",
            "Training": "Treino",
            "Experience": "Experiência",
            "Where do": "Onde",
            "you train?": "você treina?",
            "Gym": "Academia",
            "Home": "Casa",
            "Both": "Ambos",
            "Primary": "Objetivo",
            "Goal": "Principal",
            "Your Body": "Seu Corpo",
            "Measurements": "Medidas",
            "What's holding": "O que está",
            "you back?": "te impedindo?",
            "In 90 days,": "Em 90 dias,",
            "I want to...": "Eu quero...",
            "Confidence": "Confiança",
            "Referral Code": "Código de Indicação",
            "Create Your Account": "Crie Sua Conta",
            "Continue with Google": "Continuar com Google",
            "Continue with Email": "Continuar com Email",
            "Scan": "Escanear",
            "Plan": "Plano",
            "Compete": "Competir",
            "Profile": "Perfil",
            "Settings": "Configurações",
            "Log Out": "Sair",
            "Edit Profile": "Editar Perfil",
            "Cancel": "Cancelar",
            "Save": "Salvar",
            "Language": "Idioma",
            "Scans": "Escaneamentos",
            "Workouts": "Treinos",
            "Streak": "Sequência",
            "Beginner": "Iniciante",
            "Intermediate": "Intermediário",
            "Advanced": "Avançado",
            "Expert": "Especialista",
            "Notifications": "Notificações",
            "Dark Mode": "Modo Escuro",
            "Restore Purchases": "Restaurar Compras",
            "Terms & Privacy": "Termos e Privacidade",
            "Scan History": "Histórico de Scans",
            "No scans yet": "Nenhum scan ainda",
            "Limited Offer": "Oferta Limitada",
            "Remove Photo": "Remover Foto",
            "Name": "Nome",
            "Short bio (optional)": "Bio curta (opcional)",
            "Choose Your Language": "Escolha Seu Idioma",
            "Dumbbells": "Halteres",
            "Pull-up Bar": "Barra de Tração",
            "Bodyweight Only": "Apenas Peso Corporal",
            "Available equipment": "Equipamento disponível",
            "Select all that apply": "Selecione tudo que se aplica"
        ],
        "Italian": [
            "Transform Your": "Trasforma il Tuo",
            "Physique with AI": "Fisico con l'IA",
            "Get Started": "Inizia",
            "Existing user? Log in": "Già registrato? Accedi",
            "Continue": "Continua",
            "What's your": "Qual è il tuo",
            "gender?": "genere?",
            "Male": "Maschio",
            "Female": "Femmina",
            "Training": "Allenamento",
            "Experience": "Esperienza",
            "Gym": "Palestra",
            "Home": "Casa",
            "Both": "Entrambi",
            "Scan": "Scansione",
            "Plan": "Piano",
            "Compete": "Competizione",
            "Profile": "Profilo",
            "Settings": "Impostazioni",
            "Log Out": "Esci",
            "Edit Profile": "Modifica Profilo",
            "Cancel": "Annulla",
            "Save": "Salva",
            "Language": "Lingua",
            "Continue with Google": "Continua con Google",
            "Continue with Email": "Continua con Email",
            "Notifications": "Notifiche",
            "Dark Mode": "Modalità Scura",
            "Choose Your Language": "Scegli la Tua Lingua",
            "Beginner": "Principiante",
            "Intermediate": "Intermedio",
            "Advanced": "Avanzato",
            "Expert": "Esperto",
            "Scans": "Scansioni",
            "Workouts": "Allenamenti",
            "Streak": "Serie",
            "Where do": "Dove",
            "you train?": "ti alleni?",
            "How many times": "Quante volte",
            "per week?": "a settimana?",
            "Primary": "Obiettivo",
            "Goal": "Principale",
            "Your Body": "Il Tuo Corpo",
            "Measurements": "Misure",
            "Referral Code": "Codice Referral",
            "Create Your Account": "Crea il Tuo Account",
            "Dumbbells": "Manubri",
            "Pull-up Bar": "Sbarra per trazioni",
            "Bodyweight Only": "Solo peso corporeo",
            "Available equipment": "Attrezzatura disponibile"
        ],
        "Dutch": [
            "Transform Your": "Transformeer Je",
            "Physique with AI": "Lichaam met AI",
            "Get Started": "Beginnen",
            "Existing user? Log in": "Al een account? Inloggen",
            "Continue": "Doorgaan",
            "What's your": "Wat is je",
            "gender?": "geslacht?",
            "Male": "Man",
            "Female": "Vrouw",
            "Training": "Training",
            "Experience": "Ervaring",
            "Gym": "Sportschool",
            "Home": "Thuis",
            "Both": "Beide",
            "Scan": "Scan",
            "Plan": "Plan",
            "Compete": "Competitie",
            "Profile": "Profiel",
            "Settings": "Instellingen",
            "Log Out": "Uitloggen",
            "Edit Profile": "Profiel Bewerken",
            "Cancel": "Annuleren",
            "Save": "Opslaan",
            "Language": "Taal",
            "Continue with Google": "Doorgaan met Google",
            "Continue with Email": "Doorgaan met Email",
            "Notifications": "Meldingen",
            "Dark Mode": "Donkere Modus",
            "Choose Your Language": "Kies Je Taal",
            "Beginner": "Beginner",
            "Intermediate": "Gemiddeld",
            "Advanced": "Gevorderd",
            "Expert": "Expert",
            "Scans": "Scans",
            "Workouts": "Trainingen",
            "Streak": "Reeks"
        ],
        "Russian": [
            "Transform Your": "Преобразуй Своё",
            "Physique with AI": "Тело с ИИ",
            "Get Started": "Начать",
            "Existing user? Log in": "Уже есть аккаунт? Войти",
            "Continue": "Продолжить",
            "What's your": "Какой ваш",
            "gender?": "пол?",
            "Male": "Мужской",
            "Female": "Женский",
            "Training": "Тренировка",
            "Experience": "Опыт",
            "Gym": "Спортзал",
            "Home": "Дом",
            "Both": "Оба",
            "Scan": "Сканер",
            "Plan": "План",
            "Compete": "Соревнование",
            "Profile": "Профиль",
            "Settings": "Настройки",
            "Log Out": "Выйти",
            "Edit Profile": "Редактировать",
            "Cancel": "Отмена",
            "Save": "Сохранить",
            "Language": "Язык",
            "Continue with Google": "Продолжить с Google",
            "Continue with Email": "Продолжить с Email",
            "Notifications": "Уведомления",
            "Dark Mode": "Тёмный Режим",
            "Choose Your Language": "Выберите Язык",
            "Beginner": "Новичок",
            "Intermediate": "Средний",
            "Advanced": "Продвинутый",
            "Expert": "Эксперт",
            "Where do": "Где",
            "you train?": "ты тренируешься?",
            "How many times": "Сколько раз",
            "per week?": "в неделю?",
            "Scans": "Сканы",
            "Workouts": "Тренировки",
            "Streak": "Серия"
        ],
        "Japanese": [
            "Transform Your": "AIで体を",
            "Physique with AI": "トランスフォーム",
            "Get Started": "始める",
            "Existing user? Log in": "既存ユーザー？ログイン",
            "Continue": "続ける",
            "What's your": "あなたの",
            "gender?": "性別は？",
            "Male": "男性",
            "Female": "女性",
            "Training": "トレーニング",
            "Experience": "経験",
            "Gym": "ジム",
            "Home": "自宅",
            "Both": "両方",
            "Scan": "スキャン",
            "Plan": "プラン",
            "Compete": "競争",
            "Profile": "プロフィール",
            "Settings": "設定",
            "Log Out": "ログアウト",
            "Edit Profile": "プロフィール編集",
            "Cancel": "キャンセル",
            "Save": "保存",
            "Language": "言語",
            "Continue with Google": "Googleで続ける",
            "Continue with Email": "メールで続ける",
            "Notifications": "通知",
            "Dark Mode": "ダークモード",
            "Choose Your Language": "言語を選択",
            "Beginner": "初心者",
            "Intermediate": "中級者",
            "Advanced": "上級者",
            "Expert": "エキスパート",
            "Scans": "スキャン",
            "Workouts": "ワークアウト",
            "Streak": "連続記録"
        ],
        "Korean": [
            "Transform Your": "AI로 당신의",
            "Physique with AI": "체형을 변환하세요",
            "Get Started": "시작하기",
            "Existing user? Log in": "기존 사용자? 로그인",
            "Continue": "계속",
            "What's your": "당신의",
            "gender?": "성별은?",
            "Male": "남성",
            "Female": "여성",
            "Training": "트레이닝",
            "Experience": "경험",
            "Gym": "체육관",
            "Home": "홈",
            "Both": "둘 다",
            "Scan": "스캔",
            "Plan": "플랜",
            "Compete": "경쟁",
            "Profile": "프로필",
            "Settings": "설정",
            "Log Out": "로그아웃",
            "Edit Profile": "프로필 편집",
            "Cancel": "취소",
            "Save": "저장",
            "Language": "언어",
            "Continue with Google": "Google로 계속",
            "Continue with Email": "이메일로 계속",
            "Notifications": "알림",
            "Dark Mode": "다크 모드",
            "Choose Your Language": "언어 선택",
            "Beginner": "초보자",
            "Intermediate": "중급자",
            "Advanced": "고급자",
            "Expert": "전문가",
            "Scans": "스캔",
            "Workouts": "운동",
            "Streak": "연속"
        ],
        "Chinese": [
            "Transform Your": "用AI改造",
            "Physique with AI": "你的体形",
            "Get Started": "开始",
            "Existing user? Log in": "已有账户？登录",
            "Continue": "继续",
            "What's your": "你的",
            "gender?": "性别是？",
            "Male": "男",
            "Female": "女",
            "Training": "训练",
            "Experience": "经验",
            "Gym": "健身房",
            "Home": "家",
            "Both": "两者都是",
            "Scan": "扫描",
            "Plan": "计划",
            "Compete": "竞争",
            "Profile": "个人资料",
            "Settings": "设置",
            "Log Out": "退出",
            "Edit Profile": "编辑资料",
            "Cancel": "取消",
            "Save": "保存",
            "Language": "语言",
            "Continue with Google": "使用Google继续",
            "Continue with Email": "使用邮箱继续",
            "Notifications": "通知",
            "Dark Mode": "深色模式",
            "Choose Your Language": "选择语言",
            "Beginner": "初学者",
            "Intermediate": "中级",
            "Advanced": "高级",
            "Expert": "专家",
            "Scans": "扫描",
            "Workouts": "锻炼",
            "Streak": "连续"
        ],
        "Arabic": [
            "Transform Your": "حوّل جسمك",
            "Physique with AI": "بالذكاء الاصطناعي",
            "Get Started": "ابدأ",
            "Existing user? Log in": "مستخدم حالي؟ تسجيل الدخول",
            "Continue": "متابعة",
            "What's your": "ما هو",
            "gender?": "جنسك؟",
            "Male": "ذكر",
            "Female": "أنثى",
            "Training": "تدريب",
            "Experience": "خبرة",
            "Gym": "صالة رياضية",
            "Home": "المنزل",
            "Both": "كلاهما",
            "Scan": "مسح",
            "Plan": "خطة",
            "Compete": "منافسة",
            "Profile": "الملف الشخصي",
            "Settings": "الإعدادات",
            "Log Out": "تسجيل الخروج",
            "Cancel": "إلغاء",
            "Save": "حفظ",
            "Language": "اللغة",
            "Continue with Google": "المتابعة مع Google",
            "Continue with Email": "المتابعة بالبريد",
            "Notifications": "الإشعارات",
            "Dark Mode": "الوضع الداكن",
            "Choose Your Language": "اختر لغتك",
            "Beginner": "مبتدئ",
            "Intermediate": "متوسط",
            "Advanced": "متقدم",
            "Expert": "خبير",
            "Edit Profile": "تعديل الملف",
            "Scans": "عمليات المسح",
            "Workouts": "التمارين",
            "Streak": "سلسلة"
        ],
        "Hindi": [
            "Transform Your": "AI से बदलें",
            "Physique with AI": "अपना शरीर",
            "Get Started": "शुरू करें",
            "Existing user? Log in": "मौजूदा उपयोगकर्ता? लॉग इन",
            "Continue": "जारी रखें",
            "What's your": "आपका",
            "gender?": "लिंग?",
            "Male": "पुरुष",
            "Female": "महिला",
            "Training": "प्रशिक्षण",
            "Experience": "अनुभव",
            "Gym": "जिम",
            "Home": "घर",
            "Both": "दोनों",
            "Scan": "स्कैन",
            "Plan": "योजना",
            "Compete": "प्रतिस्पर्धा",
            "Profile": "प्रोफ़ाइल",
            "Settings": "सेटिंग्स",
            "Log Out": "लॉग आउट",
            "Cancel": "रद्द करें",
            "Save": "सहेजें",
            "Language": "भाषा",
            "Continue with Google": "Google से जारी रखें",
            "Continue with Email": "ईमेल से जारी रखें",
            "Notifications": "सूचनाएं",
            "Dark Mode": "डार्क मोड",
            "Choose Your Language": "अपनी भाषा चुनें",
            "Beginner": "शुरुआती",
            "Intermediate": "मध्यवर्ती",
            "Advanced": "उन्नत",
            "Expert": "विशेषज्ञ",
            "Edit Profile": "प्रोफ़ाइल संपादित",
            "Scans": "स्कैन",
            "Workouts": "कसरत",
            "Streak": "लगातार"
        ],
        "Turkish": [
            "Transform Your": "Vücudunu AI ile",
            "Physique with AI": "Dönüştür",
            "Get Started": "Başla",
            "Existing user? Log in": "Mevcut kullanıcı? Giriş yap",
            "Continue": "Devam",
            "What's your": "Cinsiyetin",
            "gender?": "nedir?",
            "Male": "Erkek",
            "Female": "Kadın",
            "Training": "Antrenman",
            "Experience": "Deneyim",
            "Gym": "Spor Salonu",
            "Home": "Ev",
            "Both": "Her İkisi",
            "Scan": "Tarama",
            "Plan": "Plan",
            "Compete": "Yarış",
            "Profile": "Profil",
            "Settings": "Ayarlar",
            "Log Out": "Çıkış",
            "Cancel": "İptal",
            "Save": "Kaydet",
            "Language": "Dil",
            "Continue with Google": "Google ile devam et",
            "Continue with Email": "Email ile devam et",
            "Notifications": "Bildirimler",
            "Dark Mode": "Karanlık Mod",
            "Choose Your Language": "Dilini Seç",
            "Beginner": "Başlangıç",
            "Intermediate": "Orta Seviye",
            "Advanced": "İleri Seviye",
            "Expert": "Uzman",
            "Edit Profile": "Profili Düzenle",
            "Scans": "Taramalar",
            "Workouts": "Antrenmanlar",
            "Streak": "Seri"
        ],
        "Polish": [
            "Transform Your": "Przekształć Swoją",
            "Physique with AI": "Sylwetkę z AI",
            "Get Started": "Rozpocznij",
            "Existing user? Log in": "Masz konto? Zaloguj się",
            "Continue": "Kontynuuj",
            "What's your": "Jaka jest twoja",
            "gender?": "płeć?",
            "Male": "Mężczyzna",
            "Female": "Kobieta",
            "Training": "Trening",
            "Experience": "Doświadczenie",
            "Gym": "Siłownia",
            "Home": "Dom",
            "Both": "Oba",
            "Scan": "Skan",
            "Plan": "Plan",
            "Compete": "Rywalizacja",
            "Profile": "Profil",
            "Settings": "Ustawienia",
            "Log Out": "Wyloguj",
            "Cancel": "Anuluj",
            "Save": "Zapisz",
            "Language": "Język",
            "Continue with Google": "Kontynuuj z Google",
            "Continue with Email": "Kontynuuj z Email",
            "Notifications": "Powiadomienia",
            "Dark Mode": "Tryb Ciemny",
            "Choose Your Language": "Wybierz Język",
            "Beginner": "Początkujący",
            "Intermediate": "Średniozaawansowany",
            "Advanced": "Zaawansowany",
            "Expert": "Ekspert",
            "Edit Profile": "Edytuj Profil",
            "Scans": "Skany",
            "Workouts": "Treningi",
            "Streak": "Seria"
        ],
        "Swedish": [
            "Transform Your": "Förvandla Din",
            "Physique with AI": "Kropp med AI",
            "Get Started": "Kom igång",
            "Existing user? Log in": "Befintlig användare? Logga in",
            "Continue": "Fortsätt",
            "What's your": "Vad är ditt",
            "gender?": "kön?",
            "Male": "Man",
            "Female": "Kvinna",
            "Training": "Träning",
            "Experience": "Erfarenhet",
            "Gym": "Gym",
            "Home": "Hemma",
            "Both": "Båda",
            "Scan": "Skanna",
            "Plan": "Plan",
            "Compete": "Tävla",
            "Profile": "Profil",
            "Settings": "Inställningar",
            "Log Out": "Logga ut",
            "Cancel": "Avbryt",
            "Save": "Spara",
            "Language": "Språk",
            "Continue with Google": "Fortsätt med Google",
            "Continue with Email": "Fortsätt med E-post",
            "Notifications": "Aviseringar",
            "Dark Mode": "Mörkt Läge",
            "Choose Your Language": "Välj Ditt Språk",
            "Beginner": "Nybörjare",
            "Intermediate": "Medel",
            "Advanced": "Avancerad",
            "Expert": "Expert",
            "Edit Profile": "Redigera Profil",
            "Scans": "Skanningar",
            "Workouts": "Träningspass",
            "Streak": "Svit"
        ],
        "Romanian": [
            "Transform Your": "Transformă-ți",
            "Physique with AI": "Fizicul cu AI",
            "Get Started": "Începe",
            "Existing user? Log in": "Ai deja cont? Conectează-te",
            "Continue": "Continuă",
            "What's your": "Care este",
            "gender?": "genul tău?",
            "Male": "Masculin",
            "Female": "Feminin",
            "Training": "Antrenament",
            "Experience": "Experiență",
            "How long have you been training?": "De cât timp te antrenezi?",
            "Beginner": "Începător",
            "Less than 6 months": "Mai puțin de 6 luni",
            "Intermediate": "Intermediar",
            "6 months – 2 years": "6 luni – 2 ani",
            "Advanced": "Avansat",
            "2+ years of training": "Peste 2 ani de antrenament",
            "Expert": "Expert",
            "Competitive level": "Nivel competitiv",
            "Gym": "Sală de sport",
            "Full equipment access": "Acces complet la echipament",
            "Home": "Acasă",
            "Bodyweight & minimal gear": "Greutate corporală și echipament minimal",
            "Both": "Ambele",
            "Mix of gym and home": "Mix de sală și acasă",
            "Scan": "Scanare",
            "Plan": "Plan",
            "Compete": "Competiție",
            "Profile": "Profil",
            "Settings": "Setări",
            "Log Out": "Deconectare",
            "Cancel": "Anulare",
            "Save": "Salvare",
            "Language": "Limbă",
            "Continue with Google": "Continuă cu Google",
            "Continue with Email": "Continuă cu Email",
            "Notifications": "Notificări",
            "Dark Mode": "Mod Întunecat",
            "Choose Your Language": "Alege-ți Limba",
            "Edit Profile": "Editare Profil",
            "Where do": "Unde",
            "you train?": "te antrenezi?",
            "How many times": "De câte ori",
            "per week?": "pe săptămână?",
            "How often do you want to train": "Cât de des vrei să te antrenezi?",
            "Primary": "Obiectiv",
            "Goal": "Principal",
            "Your Body": "Corpul Tău",
            "Measurements": "Măsurători",
            "What's holding": "Ce te",
            "you back?": "oprește?",
            "In 90 days,": "În 90 de zile,",
            "I want to...": "Vreau să...",
            "Confidence": "Încredere",
            "Referral Code": "Cod de Recomandare",
            "Create Your Account": "Creează-ți Contul",
            "Available equipment": "Echipament disponibil",
            "Dumbbells": "Gantere",
            "Pull-up Bar": "Bară de tracțiuni",
            "Bodyweight Only": "Doar greutate corporală",
            "Select all that apply": "Selectează tot ce se aplică",
            "Scans": "Scanări",
            "Workouts": "Antrenamente",
            "Streak": "Serie",
            "Scan History": "Istoricul Scanărilor",
            "No scans yet": "Nicio scanare încă",
            "Limited Offer": "Ofertă Limitată",
            "Restore Purchases": "Restaurare Achiziții",
            "Terms & Privacy": "Termeni și Confidențialitate",
            "Remove Photo": "Elimină Fotografia",
            "Name": "Nume",
            "Short bio (optional)": "Bio scurt (opțional)",
            "Sign up to save your progress": "Înscrie-te pentru a salva progresul",
            "Just starting": "Abia începând",
            "Casual": "Ocazional",
            "Moderate": "Moderat",
            "Dedicated": "Dedicat",
            "Intense": "Intens",
            "Athlete": "Atlet",
            "Every day": "În fiecare zi"
        ],
        "Hebrew": [
            "Transform Your": "שנה את",
            "Physique with AI": "הגוף שלך עם AI",
            "Get Started": "בואו נתחיל",
            "Existing user? Log in": "משתמש קיים? התחבר",
            "Continue": "המשך",
            "What's your": "מה",
            "gender?": "המגדר שלך?",
            "Male": "זכר",
            "Female": "נקבה",
            "Training": "אימון",
            "Experience": "ניסיון",
            "How long have you been training?": "כמה זמן אתה מתאמן?",
            "Beginner": "מתחיל",
            "Less than 6 months": "פחות מ-6 חודשים",
            "Intermediate": "בינוני",
            "6 months – 2 years": "6 חודשים – שנתיים",
            "Advanced": "מתקדם",
            "2+ years of training": "יותר משנתיים של אימון",
            "Expert": "מומחה",
            "Competitive level": "רמת תחרות",
            "Gym": "חדר כושר",
            "Full equipment access": "גישה מלאה לציוד",
            "Home": "בית",
            "Bodyweight & minimal gear": "משקל גוף וציוד מינימלי",
            "Both": "שניהם",
            "Mix of gym and home": "שילוב של חדר כושר ובית",
            "Scan": "סריקה",
            "Plan": "תוכנית",
            "Compete": "תחרות",
            "Profile": "פרופיל",
            "Settings": "הגדרות",
            "Log Out": "התנתק",
            "Cancel": "ביטול",
            "Save": "שמור",
            "Language": "שפה",
            "Continue with Google": "המשך עם Google",
            "Continue with Email": "המשך עם אימייל",
            "Notifications": "התראות",
            "Dark Mode": "מצב כהה",
            "Choose Your Language": "בחר שפה",
            "Edit Profile": "עריכת פרופיל",
            "Where do": "איפה",
            "you train?": "אתה מתאמן?",
            "How many times": "כמה פעמים",
            "per week?": "בשבוע?",
            "How often do you want to train": "כמה פעמים אתה רוצה להתאמן?",
            "Primary": "מטרה",
            "Goal": "עיקרית",
            "Your Body": "הגוף שלך",
            "Measurements": "מידות",
            "What's holding": "מה",
            "you back?": "מעכב אותך?",
            "In 90 days,": "בעוד 90 יום,",
            "I want to...": "אני רוצה...",
            "Confidence": "ביטחון",
            "Referral Code": "קוד הפניה",
            "Create Your Account": "צור את החשבון שלך",
            "Available equipment": "ציוד זמין",
            "Dumbbells": "משקולות יד",
            "Pull-up Bar": "מתח",
            "Bodyweight Only": "משקל גוף בלבד",
            "Select all that apply": "בחר את כל מה שמתאים",
            "Scans": "סריקות",
            "Workouts": "אימונים",
            "Streak": "רצף",
            "Scan History": "היסטוריית סריקות",
            "No scans yet": "אין סריקות עדיין",
            "Limited Offer": "הצעה מוגבלת",
            "Restore Purchases": "שחזור רכישות",
            "Terms & Privacy": "תנאים ופרטיות",
            "Remove Photo": "הסר תמונה",
            "Name": "שם",
            "Short bio (optional)": "ביו קצר (אופציונלי)",
            "Sign up to save your progress": "הירשם כדי לשמור את ההתקדמות",
            "Just starting": "רק מתחיל",
            "Casual": "מזדמן",
            "Moderate": "מתון",
            "Dedicated": "מסור",
            "Intense": "אינטנסיבי",
            "Athlete": "ספורטאי",
            "Every day": "כל יום",
            "What's your #1 focus right now?": "מה המוקד #1 שלך עכשיו?",
            "Build Muscle": "בניית שריר",
            "Gain size and strength": "צבירת גודל וכוח",
            "Lose Fat": "הפחתת שומן",
            "Lean down and cut body fat": "הרזיה והפחתת שומן",
            "Recomp": "שיפוץ",
            "Build muscle while losing fat": "בניית שריר תוך הפחתת שומן",
            "Lack of motivation": "חוסר מוטיבציה",
            "No workout plan": "אין תוכנית אימון",
            "Poor nutrition": "תזונה לקויה",
            "Inconsistency": "חוסר עקביות",
            "Time management": "ניהול זמן",
            "Injuries or pain": "פציעות או כאב",
            "Low energy": "אנרגיה נמוכה",
            "Not seeing results": "לא רואה תוצאות",
            "Gym intimidation": "הרתעה מחדר כושר",
            "Don't know where to start": "לא יודע מאיפה להתחיל",
            "Build muscle": "בניית שריר",
            "Lose fat": "הפחתת שומן",
            "Get stronger": "להתחזק",
            "Improve endurance": "שיפור סיבולת",
            "Better posture": "יציבה טובה יותר",
            "Increase flexibility": "הגברת גמישות",
            "Run a marathon": "לרוץ מרתון",
            "Feel more confident": "להרגיש יותר בטוח",
            "Build a routine": "בניית שגרה",
            "Compete in fitness": "להתחרות בכושר",
            "Just getting started": "רק מתחיל",
            "Know the basics well": "מכיר את הבסיס היטב",
            "Years of experience": "שנות ניסיון",
            "Competitive athlete level": "רמת ספורטאי תחרותי",
            "Got a code from a friend?": "קיבלת קוד מחבר?",
            "Enter code": "הזן קוד",
            "Apply & Continue": "החל והמשך",
            "I don't have a code": "אין לי קוד",
            "Imperial": "אימפריאלי",
            "Metric": "מטרי",
            "HEIGHT": "גובה",
            "WEIGHT": "משקל",
            "Choose your top goals": "בחר את היעדים המובילים",
            "How experienced are you?": "כמה אתה מנוסה?",
            "Apple Health": "Apple Health",
            "By continuing you agree to our": "בהמשך אתה מסכים ל",
            "Terms": "תנאים",
            "and": "ו",
            "Privacy Policy": "מדיניות פרטיות",
            "off Pro — Claim now": "הנחה פרו — קבל עכשיו"
        ]
    ]
}
