import Foundation

nonisolated struct L {
    static func t(_ key: String, _ language: String) -> String {
        translations[language]?[key] ?? translations["English"]?[key] ?? key
    }

    static let translations: [String: [String: String]] = [
        "English": [
            "getStarted": "Get Started",
            "continue": "Continue",
            "next": "Next",
            "save": "Save",
            "cancel": "Cancel",
            "done": "Done",
            "logIn": "Log In",
            "logOut": "Log Out",
            "alreadyHaveAccount": "Already have an account?",
            "scan": "Scan",
            "plan": "Plan",
            "compete": "Compete",
            "profile": "Profile",
            "whatsYourGender": "What's your gender?",
            "male": "Male",
            "female": "Female",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "How many times per week?",
            "howOftenTrain": "How often do you want to train",
            "trainingExperience": "Training Experience",
            "howLongTraining": "How long have you been training?",
            "whereDoYouTrain": "Where do you train?",
            "primaryGoal": "Primary Goal",
            "whatsYourFocus": "What's your #1 focus right now?",
            "whatsHoldingBack": "What's holding you back?",
            "selectAllApply": "Select all that apply",
            "in90Days": "In 90 days,",
            "iWantTo": "I want to...",
            "chooseTopGoals": "Choose your top goals",
            "trainingConfidence": "Training Confidence",
            "howExperienced": "How experienced are you?",
            "whenWereYouBorn": "When were you born?",
            "dateOfBirth": "Date of Birth",
            "yourBodyMeasurements": "Your Body Measurements",
            "settings": "Settings",
            "notifications": "Notifications",
            "darkMode": "Dark Mode",
            "appleHealth": "Apple Health",
            "language": "Language",
            "restorePurchases": "Restore Purchases",
            "termsPrivacy": "Terms & Privacy",
            "scanHistory": "Scan History",
            "noScansYet": "No scans yet",
            "comingSoon": "Coming Soon",
            "comingSoonMessage": "This feature is coming soon. Stay tuned!",
            "ok": "OK",
            "signIn": "Sign In",
            "signInApple": "Sign in with Apple",
            "signInGoogle": "Sign in with Google",
            "continueEmail": "Continue with email",
            "yourPersonalCoach": "Your personal AI fitness coach.\nScan, plan, and compete.",
            "fitAICreates": "Fit AI creates",
            "longTermResults": "long-term results",
            "height": "HEIGHT",
            "weight": "WEIGHT",
            "imperial": "Imperial",
            "metric": "Metric",
            "buildMuscle": "Build Muscle",
            "loseFat": "Lose Fat",
            "recomp": "Recomp",
            "beginner": "Beginner",
            "intermediate": "Intermediate",
            "advanced": "Advanced",
            "expert": "Expert",
            "gym": "Gym",
            "home": "Home",
            "both": "Both",
            "aiCoach": "AI Coach",
            "editProfile": "Edit Profile",
            "justStarting": "Just starting",
            "casual": "Casual",
            "moderate": "Moderate",
            "dedicated": "Dedicated",
            "intense": "Intense",
            "athlete": "Athlete",
            "everyDay": "Every day",
            "referralCode": "Referral Code",
        ],
        "Spanish": [
            "getStarted": "Comenzar",
            "continue": "Continuar",
            "next": "Siguiente",
            "save": "Guardar",
            "cancel": "Cancelar",
            "done": "Listo",
            "logIn": "Iniciar sesión",
            "logOut": "Cerrar sesión",
            "alreadyHaveAccount": "¿Ya tienes una cuenta?",
            "scan": "Escanear",
            "plan": "Plan",
            "compete": "Competir",
            "profile": "Perfil",
            "whatsYourGender": "¿Cuál es tu género?",
            "male": "Masculino",
            "female": "Femenino",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "¿Cuántas veces por semana?",
            "howOftenTrain": "¿Con qué frecuencia quieres entrenar?",
            "trainingExperience": "Experiencia de entrenamiento",
            "howLongTraining": "¿Cuánto tiempo llevas entrenando?",
            "whereDoYouTrain": "¿Dónde entrenas?",
            "primaryGoal": "Objetivo principal",
            "whatsYourFocus": "¿Cuál es tu enfoque #1?",
            "whatsHoldingBack": "¿Qué te detiene?",
            "selectAllApply": "Selecciona todo lo que aplique",
            "in90Days": "En 90 días,",
            "iWantTo": "Quiero...",
            "chooseTopGoals": "Elige tus objetivos principales",
            "trainingConfidence": "Confianza en el entrenamiento",
            "howExperienced": "¿Qué tan experimentado eres?",
            "whenWereYouBorn": "¿Cuándo naciste?",
            "dateOfBirth": "Fecha de nacimiento",
            "yourBodyMeasurements": "Tus medidas corporales",
            "settings": "Configuración",
            "notifications": "Notificaciones",
            "darkMode": "Modo oscuro",
            "appleHealth": "Apple Health",
            "language": "Idioma",
            "restorePurchases": "Restaurar compras",
            "termsPrivacy": "Términos y privacidad",
            "scanHistory": "Historial de escaneos",
            "noScansYet": "Sin escaneos aún",
            "comingSoon": "Próximamente",
            "comingSoonMessage": "Esta función estará disponible pronto.",
            "ok": "OK",
            "signIn": "Iniciar sesión",
            "signInGoogle": "Iniciar sesión con Google",
            "continueEmail": "Continuar con email",
            "yourPersonalCoach": "Tu entrenador personal de IA.\nEscanea, planifica y compite.",
            "fitAICreates": "Fit AI crea",
            "longTermResults": "resultados a largo plazo",
            "height": "ALTURA",
            "weight": "PESO",
            "imperial": "Imperial",
            "metric": "Métrico",
            "buildMuscle": "Ganar músculo",
            "loseFat": "Perder grasa",
            "recomp": "Recomposición",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzado",
            "expert": "Experto",
            "gym": "Gimnasio",
            "home": "Casa",
            "both": "Ambos",
            "aiCoach": "Coach IA",
            "editProfile": "Editar perfil",
            "justStarting": "Empezando",
            "casual": "Casual",
            "moderate": "Moderado",
            "dedicated": "Dedicado",
            "intense": "Intenso",
            "athlete": "Atleta",
            "everyDay": "Todos los días",
            "referralCode": "Código de referido",
        ],
        "French": [
            "getStarted": "Commencer",
            "continue": "Continuer",
            "next": "Suivant",
            "save": "Enregistrer",
            "cancel": "Annuler",
            "done": "Terminé",
            "logIn": "Se connecter",
            "logOut": "Déconnexion",
            "alreadyHaveAccount": "Vous avez déjà un compte?",
            "scan": "Scanner",
            "plan": "Programme",
            "compete": "Compétition",
            "profile": "Profil",
            "whatsYourGender": "Quel est votre genre?",
            "male": "Homme",
            "female": "Femme",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Combien de fois par semaine?",
            "howOftenTrain": "À quelle fréquence voulez-vous vous entraîner?",
            "trainingExperience": "Expérience d'entraînement",
            "howLongTraining": "Depuis combien de temps vous entraînez-vous?",
            "whereDoYouTrain": "Où vous entraînez-vous?",
            "primaryGoal": "Objectif principal",
            "whatsYourFocus": "Quel est votre objectif #1?",
            "whatsHoldingBack": "Qu'est-ce qui vous retient?",
            "selectAllApply": "Sélectionnez tout ce qui s'applique",
            "in90Days": "Dans 90 jours,",
            "iWantTo": "Je veux...",
            "chooseTopGoals": "Choisissez vos objectifs",
            "trainingConfidence": "Confiance en l'entraînement",
            "howExperienced": "Quel est votre niveau?",
            "whenWereYouBorn": "Quand êtes-vous né?",
            "dateOfBirth": "Date de naissance",
            "yourBodyMeasurements": "Vos mensurations",
            "settings": "Paramètres",
            "notifications": "Notifications",
            "darkMode": "Mode sombre",
            "appleHealth": "Apple Health",
            "language": "Langue",
            "restorePurchases": "Restaurer les achats",
            "termsPrivacy": "Conditions et confidentialité",
            "scanHistory": "Historique des scans",
            "noScansYet": "Aucun scan",
            "comingSoon": "Bientôt disponible",
            "comingSoonMessage": "Cette fonctionnalité sera bientôt disponible.",
            "ok": "OK",
            "signIn": "Se connecter",
            "signInGoogle": "Se connecter avec Google",
            "continueEmail": "Continuer avec email",
            "yourPersonalCoach": "Votre coach fitness IA personnel.\nScannez, planifiez et compétez.",
            "fitAICreates": "Fit AI crée",
            "longTermResults": "des résultats durables",
            "height": "TAILLE",
            "weight": "POIDS",
            "imperial": "Impérial",
            "metric": "Métrique",
            "buildMuscle": "Gagner du muscle",
            "loseFat": "Perdre du gras",
            "recomp": "Recomposition",
            "beginner": "Débutant",
            "intermediate": "Intermédiaire",
            "advanced": "Avancé",
            "expert": "Expert",
            "gym": "Salle de sport",
            "home": "Maison",
            "both": "Les deux",
            "aiCoach": "Coach IA",
            "editProfile": "Modifier le profil",
            "referralCode": "Code de parrainage",
        ],
        "German": [
            "getStarted": "Loslegen",
            "continue": "Weiter",
            "next": "Nächste",
            "save": "Speichern",
            "cancel": "Abbrechen",
            "done": "Fertig",
            "logIn": "Anmelden",
            "logOut": "Abmelden",
            "alreadyHaveAccount": "Bereits ein Konto?",
            "scan": "Scannen",
            "plan": "Plan",
            "compete": "Wettkampf",
            "profile": "Profil",
            "whatsYourGender": "Was ist dein Geschlecht?",
            "male": "Männlich",
            "female": "Weiblich",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Wie oft pro Woche?",
            "howOftenTrain": "Wie oft möchtest du trainieren?",
            "trainingExperience": "Trainingserfahrung",
            "howLongTraining": "Wie lange trainierst du schon?",
            "whereDoYouTrain": "Wo trainierst du?",
            "primaryGoal": "Hauptziel",
            "whatsYourFocus": "Was ist dein Fokus #1?",
            "whatsHoldingBack": "Was hält dich zurück?",
            "selectAllApply": "Alles Zutreffende auswählen",
            "in90Days": "In 90 Tagen,",
            "iWantTo": "möchte ich...",
            "chooseTopGoals": "Wähle deine Top-Ziele",
            "trainingConfidence": "Trainingsvertrauen",
            "howExperienced": "Wie erfahren bist du?",
            "whenWereYouBorn": "Wann bist du geboren?",
            "dateOfBirth": "Geburtsdatum",
            "yourBodyMeasurements": "Deine Körpermaße",
            "settings": "Einstellungen",
            "notifications": "Benachrichtigungen",
            "darkMode": "Dunkelmodus",
            "appleHealth": "Apple Health",
            "language": "Sprache",
            "restorePurchases": "Käufe wiederherstellen",
            "termsPrivacy": "AGB & Datenschutz",
            "scanHistory": "Scan-Verlauf",
            "noScansYet": "Noch keine Scans",
            "comingSoon": "Demnächst",
            "comingSoonMessage": "Diese Funktion kommt bald.",
            "ok": "OK",
            "signIn": "Anmelden",
            "signInGoogle": "Mit Google anmelden",
            "continueEmail": "Mit E-Mail fortfahren",
            "yourPersonalCoach": "Dein persönlicher KI-Fitness-Coach.\nScannen, planen und wetteifern.",
            "fitAICreates": "Fit AI erzielt",
            "longTermResults": "langfristige Ergebnisse",
            "height": "GRÖßE",
            "weight": "GEWICHT",
            "imperial": "Imperial",
            "metric": "Metrisch",
            "buildMuscle": "Muskeln aufbauen",
            "loseFat": "Fett verlieren",
            "recomp": "Rekomposition",
            "beginner": "Anfänger",
            "intermediate": "Fortgeschritten",
            "advanced": "Erfahren",
            "expert": "Experte",
            "gym": "Fitnessstudio",
            "home": "Zuhause",
            "both": "Beides",
            "aiCoach": "KI Coach",
            "editProfile": "Profil bearbeiten",
            "referralCode": "Empfehlungscode",
        ],
        "Portuguese": [
            "getStarted": "Começar",
            "continue": "Continuar",
            "next": "Próximo",
            "save": "Salvar",
            "cancel": "Cancelar",
            "done": "Pronto",
            "logIn": "Entrar",
            "logOut": "Sair",
            "alreadyHaveAccount": "Já tem uma conta?",
            "scan": "Escanear",
            "plan": "Plano",
            "compete": "Competir",
            "profile": "Perfil",
            "whatsYourGender": "Qual é o seu gênero?",
            "male": "Masculino",
            "female": "Feminino",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Quantas vezes por semana?",
            "howOftenTrain": "Com que frequência quer treinar?",
            "trainingExperience": "Experiência de treino",
            "howLongTraining": "Há quanto tempo você treina?",
            "whereDoYouTrain": "Onde você treina?",
            "primaryGoal": "Objetivo principal",
            "whatsYourFocus": "Qual é o seu foco #1?",
            "whatsHoldingBack": "O que te impede?",
            "selectAllApply": "Selecione tudo que se aplica",
            "in90Days": "Em 90 dias,",
            "iWantTo": "Eu quero...",
            "chooseTopGoals": "Escolha seus objetivos",
            "trainingConfidence": "Confiança no treino",
            "howExperienced": "Qual seu nível?",
            "whenWereYouBorn": "Quando você nasceu?",
            "dateOfBirth": "Data de nascimento",
            "yourBodyMeasurements": "Suas medidas corporais",
            "settings": "Configurações",
            "notifications": "Notificações",
            "darkMode": "Modo escuro",
            "language": "Idioma",
            "restorePurchases": "Restaurar compras",
            "termsPrivacy": "Termos e privacidade",
            "scanHistory": "Histórico de scans",
            "noScansYet": "Nenhum scan ainda",
            "comingSoon": "Em breve",
            "comingSoonMessage": "Este recurso estará disponível em breve.",
            "ok": "OK",
            "signIn": "Entrar",
            "signInGoogle": "Entrar com Google",
            "continueEmail": "Continuar com email",
            "yourPersonalCoach": "Seu treinador pessoal de IA.\nEscaneie, planeje e compita.",
            "fitAICreates": "Fit AI cria",
            "longTermResults": "resultados a longo prazo",
            "height": "ALTURA",
            "weight": "PESO",
            "buildMuscle": "Ganhar músculo",
            "loseFat": "Perder gordura",
            "recomp": "Recomposição",
            "beginner": "Iniciante",
            "intermediate": "Intermediário",
            "advanced": "Avançado",
            "expert": "Especialista",
            "gym": "Academia",
            "home": "Casa",
            "both": "Ambos",
            "aiCoach": "Coach IA",
            "editProfile": "Editar perfil",
            "referralCode": "Código de indicação",
        ],
        "Italian": [
            "getStarted": "Inizia",
            "continue": "Continua",
            "next": "Avanti",
            "save": "Salva",
            "cancel": "Annulla",
            "done": "Fatto",
            "logIn": "Accedi",
            "logOut": "Esci",
            "alreadyHaveAccount": "Hai già un account?",
            "scan": "Scansione",
            "plan": "Piano",
            "compete": "Competi",
            "profile": "Profilo",
            "whatsYourGender": "Qual è il tuo genere?",
            "male": "Maschio",
            "female": "Femmina",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Quante volte a settimana?",
            "howOftenTrain": "Quanto spesso vuoi allenarti?",
            "trainingExperience": "Esperienza di allenamento",
            "howLongTraining": "Da quanto tempo ti alleni?",
            "whereDoYouTrain": "Dove ti alleni?",
            "primaryGoal": "Obiettivo principale",
            "whatsYourFocus": "Qual è il tuo focus #1?",
            "whatsHoldingBack": "Cosa ti trattiene?",
            "selectAllApply": "Seleziona tutto ciò che si applica",
            "in90Days": "In 90 giorni,",
            "iWantTo": "Voglio...",
            "chooseTopGoals": "Scegli i tuoi obiettivi",
            "trainingConfidence": "Fiducia nell'allenamento",
            "howExperienced": "Qual è il tuo livello?",
            "whenWereYouBorn": "Quando sei nato?",
            "dateOfBirth": "Data di nascita",
            "yourBodyMeasurements": "Le tue misure corporee",
            "settings": "Impostazioni",
            "notifications": "Notifiche",
            "darkMode": "Modalità scura",
            "language": "Lingua",
            "restorePurchases": "Ripristina acquisti",
            "termsPrivacy": "Termini e privacy",
            "scanHistory": "Cronologia scansioni",
            "noScansYet": "Nessuna scansione",
            "comingSoon": "Prossimamente",
            "comingSoonMessage": "Questa funzione sarà disponibile a breve.",
            "ok": "OK",
            "signIn": "Accedi",
            "signInGoogle": "Accedi con Google",
            "continueEmail": "Continua con email",
            "yourPersonalCoach": "Il tuo coach fitness IA personale.\nScansiona, pianifica e competi.",
            "fitAICreates": "Fit AI crea",
            "longTermResults": "risultati a lungo termine",
            "height": "ALTEZZA",
            "weight": "PESO",
            "buildMuscle": "Aumentare massa",
            "loseFat": "Perdere grasso",
            "recomp": "Ricomposizione",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzato",
            "expert": "Esperto",
            "gym": "Palestra",
            "home": "Casa",
            "both": "Entrambi",
            "aiCoach": "Coach IA",
            "editProfile": "Modifica profilo",
            "referralCode": "Codice referral",
        ],
        "Dutch": [
            "getStarted": "Aan de slag",
            "continue": "Doorgaan",
            "next": "Volgende",
            "save": "Opslaan",
            "cancel": "Annuleren",
            "done": "Klaar",
            "logIn": "Inloggen",
            "logOut": "Uitloggen",
            "alreadyHaveAccount": "Al een account?",
            "scan": "Scannen",
            "plan": "Plan",
            "compete": "Competitie",
            "profile": "Profiel",
            "whatsYourGender": "Wat is je geslacht?",
            "male": "Man",
            "female": "Vrouw",
            "settings": "Instellingen",
            "notifications": "Meldingen",
            "darkMode": "Donkere modus",
            "language": "Taal",
            "comingSoon": "Binnenkort",
            "comingSoonMessage": "Deze functie komt binnenkort.",
            "ok": "OK",
            "whenWereYouBorn": "Wanneer ben je geboren?",
            "dateOfBirth": "Geboortedatum",
            "yourBodyMeasurements": "Je lichaamsafmetingen",
            "height": "LENGTE",
            "weight": "GEWICHT",
            "referralCode": "Verwijzingscode",
        ],
        "Russian": [
            "getStarted": "Начать",
            "continue": "Продолжить",
            "next": "Далее",
            "save": "Сохранить",
            "cancel": "Отмена",
            "done": "Готово",
            "logIn": "Войти",
            "logOut": "Выйти",
            "alreadyHaveAccount": "Уже есть аккаунт?",
            "scan": "Сканирование",
            "plan": "План",
            "compete": "Соревнование",
            "profile": "Профиль",
            "whatsYourGender": "Ваш пол?",
            "male": "Мужской",
            "female": "Женский",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Сколько раз в неделю?",
            "howOftenTrain": "Как часто вы хотите тренироваться?",
            "trainingExperience": "Опыт тренировок",
            "howLongTraining": "Как давно вы тренируетесь?",
            "whereDoYouTrain": "Где вы тренируетесь?",
            "primaryGoal": "Главная цель",
            "whatsYourFocus": "Ваш главный фокус?",
            "whatsHoldingBack": "Что вас сдерживает?",
            "selectAllApply": "Выберите все подходящие",
            "in90Days": "Через 90 дней,",
            "iWantTo": "Я хочу...",
            "trainingConfidence": "Уверенность в тренировках",
            "howExperienced": "Ваш уровень опыта?",
            "whenWereYouBorn": "Когда вы родились?",
            "dateOfBirth": "Дата рождения",
            "yourBodyMeasurements": "Ваши параметры тела",
            "settings": "Настройки",
            "notifications": "Уведомления",
            "darkMode": "Тёмная тема",
            "language": "Язык",
            "restorePurchases": "Восстановить покупки",
            "termsPrivacy": "Условия и конфиденциальность",
            "scanHistory": "История сканирований",
            "noScansYet": "Нет сканирований",
            "comingSoon": "Скоро",
            "comingSoonMessage": "Эта функция скоро будет доступна.",
            "ok": "OK",
            "signIn": "Войти",
            "signInGoogle": "Войти через Google",
            "continueEmail": "Продолжить с email",
            "yourPersonalCoach": "Ваш персональный ИИ фитнес-тренер.\nСканируйте, планируйте и соревнуйтесь.",
            "fitAICreates": "Fit AI создаёт",
            "longTermResults": "долгосрочные результаты",
            "height": "РОСТ",
            "weight": "ВЕС",
            "buildMuscle": "Набрать мышцы",
            "loseFat": "Сжечь жир",
            "gym": "Зал",
            "home": "Дома",
            "both": "Оба варианта",
            "aiCoach": "ИИ Тренер",
            "editProfile": "Редактировать профиль",
            "referralCode": "Реферальный код",
        ],
        "Japanese": [
            "getStarted": "始める",
            "continue": "続ける",
            "next": "次へ",
            "save": "保存",
            "cancel": "キャンセル",
            "done": "完了",
            "logIn": "ログイン",
            "logOut": "ログアウト",
            "alreadyHaveAccount": "アカウントをお持ちですか？",
            "scan": "スキャン",
            "plan": "プラン",
            "compete": "競争",
            "profile": "プロフィール",
            "whatsYourGender": "性別は？",
            "male": "男性",
            "female": "女性",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "週に何回？",
            "howOftenTrain": "どのくらいの頻度でトレーニングしますか？",
            "trainingExperience": "トレーニング経験",
            "whereDoYouTrain": "どこでトレーニングしますか？",
            "primaryGoal": "メインの目標",
            "whatsHoldingBack": "何が障害ですか？",
            "in90Days": "90日後に、",
            "iWantTo": "私は...",
            "trainingConfidence": "トレーニングの自信",
            "whenWereYouBorn": "いつ生まれましたか？",
            "dateOfBirth": "生年月日",
            "yourBodyMeasurements": "あなたの体の計測値",
            "settings": "設定",
            "notifications": "通知",
            "darkMode": "ダークモード",
            "language": "言語",
            "comingSoon": "近日公開",
            "comingSoonMessage": "この機能は近日公開予定です。",
            "ok": "OK",
            "signIn": "サインイン",
            "yourPersonalCoach": "あなた専属のAIフィットネスコーチ。\nスキャン、プラン、競争。",
            "fitAICreates": "Fit AIが生み出す",
            "longTermResults": "長期的な結果",
            "height": "身長",
            "weight": "体重",
            "buildMuscle": "筋肉増強",
            "loseFat": "脂肪燃焼",
            "gym": "ジム",
            "home": "自宅",
            "both": "両方",
            "aiCoach": "AIコーチ",
            "editProfile": "プロフィール編集",
            "referralCode": "紹介コード",
        ],
        "Korean": [
            "getStarted": "시작하기",
            "continue": "계속",
            "next": "다음",
            "save": "저장",
            "cancel": "취소",
            "done": "완료",
            "logIn": "로그인",
            "logOut": "로그아웃",
            "alreadyHaveAccount": "이미 계정이 있으신가요?",
            "scan": "스캔",
            "plan": "플랜",
            "compete": "경쟁",
            "profile": "프로필",
            "whatsYourGender": "성별이 무엇인가요?",
            "male": "남성",
            "female": "여성",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "일주일에 몇 번?",
            "trainingExperience": "운동 경험",
            "whereDoYouTrain": "어디서 운동하나요?",
            "primaryGoal": "주요 목표",
            "whatsHoldingBack": "무엇이 방해하나요?",
            "in90Days": "90일 후,",
            "iWantTo": "나는...",
            "trainingConfidence": "운동 자신감",
            "whenWereYouBorn": "언제 태어났나요?",
            "dateOfBirth": "생년월일",
            "yourBodyMeasurements": "신체 치수",
            "settings": "설정",
            "notifications": "알림",
            "darkMode": "다크 모드",
            "language": "언어",
            "comingSoon": "곧 출시",
            "comingSoonMessage": "이 기능은 곧 출시됩니다.",
            "ok": "확인",
            "signIn": "로그인",
            "yourPersonalCoach": "당신의 개인 AI 피트니스 코치.\n스캔, 계획, 경쟁.",
            "fitAICreates": "Fit AI가 만드는",
            "longTermResults": "장기적인 결과",
            "height": "키",
            "weight": "체중",
            "buildMuscle": "근육 증가",
            "loseFat": "체지방 감소",
            "gym": "헬스장",
            "home": "홈",
            "both": "모두",
            "aiCoach": "AI 코치",
            "editProfile": "프로필 수정",
            "referralCode": "추천 코드",
        ],
        "Chinese": [
            "getStarted": "开始",
            "continue": "继续",
            "next": "下一步",
            "save": "保存",
            "cancel": "取消",
            "done": "完成",
            "logIn": "登录",
            "logOut": "退出",
            "alreadyHaveAccount": "已有账号？",
            "scan": "扫描",
            "plan": "计划",
            "compete": "竞赛",
            "profile": "个人资料",
            "whatsYourGender": "你的性别是？",
            "male": "男",
            "female": "女",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "每周几次？",
            "trainingExperience": "训练经验",
            "whereDoYouTrain": "你在哪里训练？",
            "primaryGoal": "主要目标",
            "whatsHoldingBack": "什么在阻碍你？",
            "in90Days": "90天后，",
            "iWantTo": "我想...",
            "trainingConfidence": "训练信心",
            "whenWereYouBorn": "你什么时候出生的？",
            "dateOfBirth": "出生日期",
            "yourBodyMeasurements": "你的身体数据",
            "settings": "设置",
            "notifications": "通知",
            "darkMode": "深色模式",
            "language": "语言",
            "comingSoon": "即将推出",
            "comingSoonMessage": "此功能即将推出。",
            "ok": "好的",
            "signIn": "登录",
            "yourPersonalCoach": "你的私人AI健身教练。\n扫描、计划、竞赛。",
            "fitAICreates": "Fit AI 创造",
            "longTermResults": "长期效果",
            "height": "身高",
            "weight": "体重",
            "buildMuscle": "增肌",
            "loseFat": "减脂",
            "gym": "健身房",
            "home": "家里",
            "both": "两者",
            "aiCoach": "AI教练",
            "editProfile": "编辑资料",
            "referralCode": "推荐码",
        ],
        "Arabic": [
            "getStarted": "ابدأ",
            "continue": "متابعة",
            "next": "التالي",
            "save": "حفظ",
            "cancel": "إلغاء",
            "done": "تم",
            "logIn": "تسجيل الدخول",
            "logOut": "تسجيل الخروج",
            "alreadyHaveAccount": "لديك حساب بالفعل؟",
            "scan": "مسح",
            "plan": "خطة",
            "compete": "منافسة",
            "profile": "الملف الشخصي",
            "whatsYourGender": "ما هو جنسك؟",
            "male": "ذكر",
            "female": "أنثى",
            "gymRat": "GymRat",
            "whenWereYouBorn": "متى ولدت؟",
            "dateOfBirth": "تاريخ الميلاد",
            "yourBodyMeasurements": "قياسات جسمك",
            "settings": "الإعدادات",
            "notifications": "الإشعارات",
            "darkMode": "الوضع الداكن",
            "language": "اللغة",
            "comingSoon": "قريباً",
            "comingSoonMessage": "هذه الميزة قادمة قريباً.",
            "ok": "حسناً",
            "signIn": "تسجيل الدخول",
            "yourPersonalCoach": "مدربك الشخصي بالذكاء الاصطناعي.\nامسح، خطط، وتنافس.",
            "height": "الطول",
            "weight": "الوزن",
            "aiCoach": "مدرب IA",
            "referralCode": "رمز الإحالة",
        ],
        "Hindi": [
            "getStarted": "शुरू करें",
            "continue": "जारी रखें",
            "next": "अगला",
            "save": "सहेजें",
            "cancel": "रद्द करें",
            "done": "हो गया",
            "logIn": "लॉग इन",
            "logOut": "लॉग आउट",
            "alreadyHaveAccount": "पहले से अकाउंट है?",
            "scan": "स्कैन",
            "plan": "योजना",
            "compete": "प्रतिस्पर्धा",
            "profile": "प्रोफ़ाइल",
            "whatsYourGender": "आपका लिंग क्या है?",
            "male": "पुरुष",
            "female": "महिला",
            "whenWereYouBorn": "आपका जन्म कब हुआ?",
            "dateOfBirth": "जन्म तिथि",
            "settings": "सेटिंग्स",
            "notifications": "सूचनाएं",
            "darkMode": "डार्क मोड",
            "language": "भाषा",
            "comingSoon": "जल्द आ रहा है",
            "comingSoonMessage": "यह सुविधा जल्द ही उपलब्ध होगी।",
            "ok": "ठीक है",
            "signIn": "साइन इन",
            "height": "ऊंचाई",
            "weight": "वजन",
            "aiCoach": "AI कोच",
            "referralCode": "रेफरल कोड",
        ],
        "Turkish": [
            "getStarted": "Başla",
            "continue": "Devam",
            "next": "İleri",
            "save": "Kaydet",
            "cancel": "İptal",
            "done": "Tamam",
            "logIn": "Giriş Yap",
            "logOut": "Çıkış Yap",
            "alreadyHaveAccount": "Zaten hesabın var mı?",
            "scan": "Tarama",
            "plan": "Plan",
            "compete": "Yarış",
            "profile": "Profil",
            "whatsYourGender": "Cinsiyetin nedir?",
            "male": "Erkek",
            "female": "Kadın",
            "gymRat": "GymRat",
            "howManyTimesPerWeek": "Haftada kaç kez?",
            "trainingExperience": "Antrenman deneyimi",
            "whereDoYouTrain": "Nerede antrenman yapıyorsun?",
            "primaryGoal": "Ana hedef",
            "whatsHoldingBack": "Seni ne engelliyor?",
            "in90Days": "90 gün içinde,",
            "trainingConfidence": "Antrenman güveni",
            "whenWereYouBorn": "Ne zaman doğdun?",
            "dateOfBirth": "Doğum tarihi",
            "yourBodyMeasurements": "Vücut ölçülerin",
            "settings": "Ayarlar",
            "notifications": "Bildirimler",
            "darkMode": "Karanlık mod",
            "language": "Dil",
            "comingSoon": "Yakında",
            "comingSoonMessage": "Bu özellik yakında geliyor.",
            "ok": "Tamam",
            "signIn": "Giriş Yap",
            "yourPersonalCoach": "Kişisel AI fitness koçun.\nTara, planla ve yarış.",
            "height": "BOY",
            "weight": "KİLO",
            "buildMuscle": "Kas yap",
            "loseFat": "Yağ yak",
            "gym": "Spor salonu",
            "home": "Ev",
            "both": "İkisi de",
            "aiCoach": "AI Koç",
            "editProfile": "Profili düzenle",
            "referralCode": "Referans kodu",
        ],
        "Polish": [
            "getStarted": "Zacznij",
            "continue": "Kontynuuj",
            "next": "Dalej",
            "save": "Zapisz",
            "cancel": "Anuluj",
            "done": "Gotowe",
            "logIn": "Zaloguj się",
            "logOut": "Wyloguj się",
            "scan": "Skan",
            "plan": "Plan",
            "compete": "Rywalizuj",
            "profile": "Profil",
            "settings": "Ustawienia",
            "notifications": "Powiadomienia",
            "darkMode": "Tryb ciemny",
            "language": "Język",
            "comingSoon": "Wkrótce",
            "comingSoonMessage": "Ta funkcja pojawi się wkrótce.",
            "ok": "OK",
            "whenWereYouBorn": "Kiedy się urodziłeś?",
            "dateOfBirth": "Data urodzenia",
            "height": "WZROST",
            "weight": "WAGA",
            "referralCode": "Kod polecający",
        ],
        "Swedish": [
            "getStarted": "Kom igång",
            "continue": "Fortsätt",
            "next": "Nästa",
            "save": "Spara",
            "cancel": "Avbryt",
            "done": "Klar",
            "logIn": "Logga in",
            "logOut": "Logga ut",
            "scan": "Skanna",
            "plan": "Plan",
            "compete": "Tävla",
            "profile": "Profil",
            "settings": "Inställningar",
            "notifications": "Aviseringar",
            "darkMode": "Mörkt läge",
            "language": "Språk",
            "comingSoon": "Kommer snart",
            "comingSoonMessage": "Den här funktionen kommer snart.",
            "ok": "OK",
            "whenWereYouBorn": "När föddes du?",
            "dateOfBirth": "Födelsedatum",
            "height": "LÄNGD",
            "weight": "VIKT",
            "referralCode": "Hänvisningskod",
        ],
        "Romanian": [
            "getStarted": "Începe",
            "continue": "Continuă",
            "next": "Următorul",
            "save": "Salvează",
            "cancel": "Anulează",
            "done": "Gata",
            "logIn": "Conectare",
            "logOut": "Deconectare",
            "scan": "Scanare",
            "plan": "Plan",
            "compete": "Concurează",
            "profile": "Profil",
            "settings": "Setări",
            "notifications": "Notificări",
            "darkMode": "Mod întunecat",
            "language": "Limbă",
            "comingSoon": "În curând",
            "comingSoonMessage": "Această funcție vine în curând.",
            "ok": "OK",
            "whenWereYouBorn": "Când te-ai născut?",
            "dateOfBirth": "Data nașterii",
            "height": "ÎNĂLȚIME",
            "weight": "GREUTATE",
            "referralCode": "Cod de referință",
        ],
        "Hebrew": [
            "getStarted": "התחל",
            "continue": "המשך",
            "next": "הבא",
            "save": "שמור",
            "cancel": "ביטול",
            "done": "סיום",
            "logIn": "התחברות",
            "logOut": "התנתקות",
            "scan": "סריקה",
            "plan": "תוכנית",
            "compete": "תחרות",
            "profile": "פרופיל",
            "settings": "הגדרות",
            "notifications": "התראות",
            "darkMode": "מצב כהה",
            "language": "שפה",
            "comingSoon": "בקרוב",
            "comingSoonMessage": "תכונה זו תהיה זמינה בקרוב.",
            "ok": "אישור",
            "whenWereYouBorn": "מתי נולדת?",
            "dateOfBirth": "תאריך לידה",
            "height": "גובה",
            "weight": "משקל",
            "referralCode": "קוד הפניה",
        ],
    ]
}
