import Foundation

nonisolated struct L {
    static func t(_ key: String, _ language: String) -> String {
        translations[language]?[key] ?? translations["English"]?[key] ?? key
    }

    static let translations: [String: [String: String]] = [
        "English": [
            "getStarted": "Get Started",
            "continue": "Continue",
            "next": "Next",
            "save": "Save",
            "cancel": "Cancel",
            "done": "Done",
            "close": "Close",
            "logIn": "Log In",
            "logOut": "Log Out",
            "alreadyHaveAccount": "Already have an account?",
            "scan": "Scan",
            "plan": "Plan",
            "compete": "Compete",
            "profile": "Profile",
            "ok": "OK",

            // Welcome
            "yourPersonalCoach": "Your personal AI\nfitness coach.",
            "scanPlanCompete": "Scan, plan, and compete.",
            "byContinuingAgree": "By continuing you agree to our",
            "terms": "Terms",
            "and": "and",
            "privacyPolicy": "Privacy Policy",

            // Sign Up
            "signIn": "Sign In",
            "signInApple": "Sign in with Apple",
            "signInGoogle": "Sign in with Google",
            "continueEmail": "Continue with email",
            "byContinuingFitAI": "By continuing you agree to Fit AI's",
            "termsAndConditions": "Terms and Conditions",

            // Gender
            "whatsYourGender": "What's your",
            "gender": "gender?",
            "male": "Male",
            "female": "Female",
            "gymRat": "GymRat",

            // Workouts per week
            "howManyTimes": "How many times",
            "perWeek": "per week?",
            "howOftenTrain": "How often do you want to train",
            "justStarting": "Just starting",
            "casual": "Casual",
            "moderate": "Moderate",
            "dedicated": "Dedicated",
            "intense": "Intense",
            "athlete": "Athlete",
            "everyDay": "Every day",

            // Training Experience
            "training": "Training",
            "experience": "Experience",
            "howLongTraining": "How long have you been training?",
            "beginner": "Beginner",
            "intermediate": "Intermediate",
            "advanced": "Advanced",
            "expert": "Expert",
            "lessThan6Months": "Less than 6 months",
            "sixMonthsTo2Years": "6 months – 2 years",
            "twoYearsPlus": "2+ years of training",
            "competitiveLevel": "Competitive level",

            // Training Location
            "whereDoYou": "Where do",
            "youTrain": "you train?",
            "gym": "Gym",
            "home": "Home",
            "both": "Both",
            "fullEquipment": "Full equipment access",
            "bodyweightMinimal": "Bodyweight & minimal gear",
            "mixGymHome": "Mix of gym and home",
            "availableEquipment": "Available equipment",
            "dumbbells": "Dumbbells",
            "pullUpBar": "Pull-up Bar",
            "bodyweightOnly": "Bodyweight Only",

            // Primary Goal
            "primary": "Primary",
            "goal": "Goal",
            "whatsYourFocus": "What's your #1 focus right now?",
            "buildMuscle": "Build Muscle",
            "loseFat": "Lose Fat",
            "recomp": "Recomp",
            "gainSizeStrength": "Gain size and strength",
            "leanDownCut": "Lean down and cut body fat",
            "buildMuscleLoseFat": "Build muscle while losing fat",

            // Holding Back
            "whatsHolding": "What's holding",
            "youBack": "you back?",
            "selectAllApply": "Select all that apply",
            "lackMotivation": "Lack of motivation",
            "noWorkoutPlan": "No workout plan",
            "poorNutrition": "Poor nutrition",
            "inconsistency": "Inconsistency",
            "timeManagement": "Time management",
            "injuriesPain": "Injuries or pain",
            "lowEnergy": "Low energy",
            "notSeeingResults": "Not seeing results",
            "gymIntimidation": "Gym intimidation",
            "dontKnowStart": "Don't know where to start",

            // Goals
            "in90Days": "In 90 days,",
            "iWantTo": "I want to...",
            "chooseTopGoals": "Choose your top goals",
            "buildMuscleGoal": "Build muscle",
            "loseFatGoal": "Lose fat",
            "getStronger": "Get stronger",
            "improveEndurance": "Improve endurance",
            "betterPosture": "Better posture",
            "increaseFlexibility": "Increase flexibility",
            "runMarathon": "Run a marathon",
            "feelConfident": "Feel more confident",
            "buildRoutine": "Build a routine",
            "competeInFitness": "Compete in fitness",

            // Confidence
            "trainingConfidence": "Training",
            "confidence": "Confidence",
            "howExperienced": "How experienced are you?",
            "justGettingStarted": "Just getting started",
            "knowBasicsWell": "Know the basics well",
            "yearsOfExperience": "Years of experience",
            "competitiveAthleteLevel": "Competitive athlete level",

            // Date of Birth
            "whenWere": "When were",
            "youBorn": "you born?",
            "helpsPersonalize": "This helps us personalize your plan",
            "yearsOld": "years old",

            // Height Weight
            "yourBody": "Your Body",
            "measurements": "Measurements",
            "height": "HEIGHT",
            "weight": "WEIGHT",
            "imperial": "Imperial",
            "metric": "Metric",

            // Referral
            "referralCode": "Referral Code",
            "gotCodeFriend": "Got a code from a friend? Enter it below.",
            "enterCode": "Enter code",
            "codeEntered": "Code entered",
            "applyAndContinue": "Apply & Continue",
            "noCode": "I don't have a code",

            // Results Graph
            "fitAICreates": "Fit AI creates",
            "longTermResults": "long-term results",
            "yourPhysique": "Your Physique",
            "month1": "Month 1",
            "month6": "Month 6",
            "fitAITraining": "Fit AI Training",
            "traditionalTraining": "Traditional Training",
            "usersMainGains": "80% of Fit AI users maintain their\nphysique gains even 6 months later",

            // Spin Wheel
            "spinToWin": "Spin to Win",
            "getExclusiveDiscount": "Get an exclusive discount",
            "spinTheWheel": "Spin the Wheel",
            "noThanks": "No thanks",

            // Paywall
            "unlockFitAIPro": "Unlock Fit AI Pro",
            "premiumExperience": "Your premium AI fitness experience",
            "aiWorkoutPlans": "AI Workout Plans",
            "personalizedGoals": "Personalized to your goals",
            "bodyCompositionScans": "Body Composition Scans",
            "unlimitedAnalysis": "Unlimited AI-powered analysis",
            "progressTracking": "Progress Tracking",
            "detailedAnalytics": "Detailed analytics & insights",
            "competeAndEarn": "Compete & Earn",
            "leaderboardsChallenges": "Leaderboards & challenges",
            "priorityAICoach": "Priority AI Coach",
            "fasterSmarter": "Faster, smarter recommendations",
            "monthly": "Monthly",
            "annual": "Annual",
            "lifetime": "Lifetime",
            "perMonth": "/month",
            "perYear": "/year",
            "oneTime": "one-time",
            "bestValue": "BEST VALUE",
            "startFreeTrial": "Start 3-Day Free Trial",
            "cancelAnytime": "Cancel anytime. No commitment.",

            // Scan View
            "latestScore": "Latest score",
            "noScanYet": "No scan yet",
            "readyToScan": "Ready to Scan",
            "uploadPhotos": "Upload your physique photos for AI analysis",
            "front": "Front",
            "back": "Back",
            "optional": "Optional",
            "analyzing": "Analyzing...",
            "analyzeWithAI": "Analyze with AI",
            "pro": "(Pro)",
            "photoGuidelines": "Photo guidelines",
            "tipsForBetterScan": "Tips for a better scan",
            "goodLighting": "Good, even lighting",
            "neutralPose": "Neutral standing pose",
            "torsoVisible": "Torso or full body visible",
            "plainBackground": "Plain background if possible",
            "ninetyDayTransformation": "90-Day Transformation",
            "seePotentialPhysique": "See your potential physique with AI",
            "tapToViewFull": "Tap to view full",
            "generating": "Generating...",
            "regenerate": "Regenerate",
            "generatePreview": "Generate Preview",
            "results": "Results",
            "strengths": "Strengths",
            "areasToImprove": "Areas to Improve",
            "summary": "Summary",
            "recommendations": "Recommendations",
            "potential": "Potential",
            "muscleMass": "Muscle Mass",
            "ratings": "Ratings",
            "saved": "Saved",
            "share": "Share",
            "excellent": "Excellent",
            "great": "Great",
            "good": "Good",
            "average": "Average",
            "needsWork": "Needs Work",
            "transformation": "Transformation",
            "your90DayPotential": "Your 90-Day Potential",
            "generatingTransformation": "Generating your 90-day transformation...",
            "mayTakeMinute": "This may take up to a minute",
            "couldNotGenerate": "Could not generate transformation",
            "resultsDisclaimer": "Results may vary. This is an AI-generated visualization for motivation purposes.",
            "choosePhoto": "Choose Photo",
            "takePhoto": "Take Photo",
            "chooseFromLibrary": "Choose from Library",

            // Plan View
            "yourPlanBasedOn": "Your Plan is based on",
            "todaysGoal": "TODAY'S GOAL",
            "restAndRecover": "Rest & Recover",
            "startWorkout": "Start Workout",
            "xpReward": "XP Reward",
            "target": "Target",
            "weeklyStreak": "Weekly Streak",
            "perfectWeek": "Perfect Week!",
            "scanInsight": "Scan Insight",
            "focusOn": "Focus on",
            "lookingStrong": "looking strong",
            "score": "Score",
            "onTrack": "On Track",
            "scanOverdue": "Scan Overdue",
            "scanToPersonalize": "Scan to Personalize",
            "completeScanForPlan": "Complete a body scan to get a workout plan\ntailored to your weak points",
            "focusAreas": "Focus Areas",
            "thisWeek": "This Week",
            "competeBonus": "Compete Bonus",
            "points": "Points",
            "streak": "Streak",
            "rank": "Rank",
            "nextScanDays": "Next scan in %@ days",
            "timeForNewScan": "Time for a new scan!",
            "keepConsistent": "Keep consistent for best accuracy",
            "completeFirstScan": "Complete your first scan",
            "trackProgress": "Track progress with regular scans",
            "workouts": "Workouts",
            "dayStreak": "Day Streak",
            "xpEarned": "XP Earned",
            "improvementAreas": "Improvement areas",
            "doneLabel": "DONE",
            "focusLabel": "FOCUS",

            // Compete View
            "xp": "XP",
            "wins": "wins",
            "season": "SEASON",
            "daysRemaining": "days remaining",
            "ends": "ENDS",
            "activeChallenge": "ACTIVE CHALLENGE",
            "weeklyWarrior": "Weekly Warrior",
            "completeAllWorkouts": "Complete all %@ planned workouts this week",
            "physiqueBattle": "1v1 Physique Battle",
            "battleSubtitle": "Upload photos • AI judges • Get mogged 💀",
            "you": "YOU",
            "vs": "VS",
            "week": "Week",
            "train": "Train",
            "move": "Move",
            "challenges": "Challenges",
            "showLess": "Show Less",
            "showAllChallenges": "Show All %@ Challenges",
            "leaderboard": "Leaderboard",
            "achievements": "Achievements",
            "activity": "Activity",
            "recent": "Recent",
            "sevenDayStreak": "7-Day Streak",
            "workOut7Days": "Work out 7 days in a row",
            "firstScan": "First Scan",
            "completeFirstBodyScan": "Complete your first body scan",
            "ironWill": "Iron Will",
            "complete10Workouts": "Complete 10 total workouts",
            "earlyRiser": "Early Riser",
            "fiveWorkoutsBefore9": "5 workouts before 9 AM",
            "mysteryChallenge": "??? Mystery",
            "unlockAfter3Wins": "Unlock after 3 challenge wins",
            "firstBlood": "First Blood",
            "winFirstBattle": "Win your first battle",
            "weekWarrior": "Week Warrior",
            "sevenDayWorkoutStreak": "7-day workout streak",
            "gladiator": "Gladiator",
            "complete10Battles": "Complete 10 battles",
            "complete25Workouts": "Complete 25 workouts",
            "unstoppable": "Unstoppable",
            "thirtyDayStreak": "30-day streak",
            "diamondLeague": "Diamond League",
            "reachDiamondTier": "Reach Diamond tier",
            "dLeft": "%@d left",
            "high": "High",
            "medium": "Medium",
            "bonus": "Bonus",
            "locked": "Locked",

            // Coach View
            "aiCoach": "AI Coach",
            "yourAICoach": "Your AI Coach",
            "askAnythingFitness": "Ask me anything about fitness, nutrition,\nrecovery, or your workout plan.",
            "tryAsking": "Try asking",
            "askYourCoach": "Ask your coach...",
            "whatEatPostWorkout": "What should I eat post-workout?",
            "howImproveBench": "How do I improve my bench press?",
            "bestWayLoseFat": "Best way to lose fat and build muscle?",
            "howMuchProtein": "How much protein do I need daily?",
            "createMealPlan": "Create a meal plan for muscle gain",
            "howFixShoulders": "How to fix rounded shoulders?",

            // Profile
            "settings": "Settings",
            "notifications": "Notifications",
            "darkMode": "Dark Mode",
            "appleHealth": "Apple Health",
            "language": "Language",
            "restorePurchases": "Restore Purchases",
            "termsPrivacy": "Terms & Privacy",
            "scanHistory": "Scan History",
            "noScansYet": "No scans yet",
            "comingSoon": "Coming Soon",
            "comingSoonMessage": "This feature is coming soon. Stay tuned!",
            "editProfile": "Edit Profile",
            "scans": "Scans",
            "limitedOffer": "Limited Offer",
            "offProClaim": "%@%% off Pro — Claim now",
            "name": "Name",
            "shortBio": "Short bio (optional)",
            "removePhoto": "Remove Photo",
            "streakDaysCount": "Streak: %@ days",
            "toNextTier": "to %@",
            "focusOnArea": "Focus on %@",
            "lookingStrongArea": "%@ looking strong",
            "scannedDaysAgo": "Scanned %@ days ago",
            "consistencyPercent": "Consistency: %@%%",
            "completeForPointsMsg": "Complete %@ to earn +%@ Compete points",
            "timesPerWeek": "%@x/week",
            "hard": "Hard",
            "medium": "Medium",
            "easy": "Easy",
            "exercises": "Exercises",
            "totalSets": "Total Sets",
            "estTime": "Est. Time",
            "completedStatus": "Completed",
            "inProgressStatus": "In Progress",
            "completeWorkout": "Complete Workout",
            "finishEarly": "Finish Early",
            "tips": "Tips",
            "workoutCompleteTitle": "Workout Complete!",
            "finishButton": "Finish",
            "workoutCompleteMsg": "You completed %@/%@ exercises in %@ minutes. +%@ points!",
            "setsLabel": "sets",
            "currentScore": "Current Score",
            "whyThisMatters": "Why This Matters",
            "recommendedExercises": "Recommended Exercises",
            "highPriority": "High Priority",
            "moderateLabel": "Moderate",
            "maintainingLabel": "Maintaining",
            "oneVOneBattle": "1v1 Battle",
            "opponentLabel": "Opponent",
            "battleDesc": "Upload both physique photos and let AI decide who gets mogged",
            "opponentNameLabel": "Opponent's Name",
            "enterNamePlaceholder": "Enter name",
            "addPhoto": "Add Photo",
            "startBattle": "Start Battle",
            "physiqueBattleHeader": "PHYSIQUE BATTLE",
            "moggedStamp": "MOGGED",
            "overallScoreLabel": "Overall Score",
            "muscleBreakdown": "Muscle Breakdown",
            "shareBattleCard": "Share Battle Card",
            "winsBy": "%@ wins by %@ points!",
            "shareBattle": "Share Battle",
            "overallLabel": "Overall",
            "tipRest": "Rest 60-90s between sets for hypertrophy",
            "tipEccentric": "Focus on controlled eccentric (lowering) phase",
            "tipHydration": "Stay hydrated — aim for water between sets",
            "tipWeakPoints": "Extra volume on weak points accelerates growth",
            "youLabel": "(You)",
            "todayLabel": "today",
            "xpToNextTier": "%@ XP to %@",
            "focusBadge": "FOCUS",
            "doneBadge": "DONE",
            "winterBulk": "Winter Bulk",
            "springCut": "Spring Cut",
            "summerShred": "Summer Shred",
            "fallGains": "Fall Gains",
        ],

        "Spanish": [
            "getStarted": "Comenzar",
            "continue": "Continuar",
            "next": "Siguiente",
            "save": "Guardar",
            "cancel": "Cancelar",
            "done": "Listo",
            "close": "Cerrar",
            "logIn": "Iniciar sesión",
            "logOut": "Cerrar sesión",
            "alreadyHaveAccount": "¿Ya tienes una cuenta?",
            "scan": "Escanear",
            "plan": "Plan",
            "compete": "Competir",
            "profile": "Perfil",
            "ok": "OK",
            "yourPersonalCoach": "Tu entrenador personal\nde IA.",
            "scanPlanCompete": "Escanea, planifica y compite.",
            "byContinuingAgree": "Al continuar aceptas nuestros",
            "terms": "Términos",
            "and": "y",
            "privacyPolicy": "Política de privacidad",
            "signIn": "Iniciar sesión",
            "signInGoogle": "Iniciar sesión con Google",
            "continueEmail": "Continuar con email",
            "byContinuingFitAI": "Al continuar aceptas los",
            "termsAndConditions": "Términos y condiciones",
            "whatsYourGender": "¿Cuál es tu",
            "gender": "género?",
            "male": "Masculino",
            "female": "Femenino",
            "gymRat": "GymRat",
            "howManyTimes": "¿Cuántas veces",
            "perWeek": "por semana?",
            "howOftenTrain": "¿Con qué frecuencia quieres entrenar?",
            "justStarting": "Empezando",
            "casual": "Casual",
            "moderate": "Moderado",
            "dedicated": "Dedicado",
            "intense": "Intenso",
            "athlete": "Atleta",
            "everyDay": "Todos los días",
            "training": "Experiencia de",
            "experience": "Entrenamiento",
            "howLongTraining": "¿Cuánto tiempo llevas entrenando?",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzado",
            "expert": "Experto",
            "lessThan6Months": "Menos de 6 meses",
            "sixMonthsTo2Years": "6 meses – 2 años",
            "twoYearsPlus": "Más de 2 años",
            "competitiveLevel": "Nivel competitivo",
            "whereDoYou": "¿Dónde",
            "youTrain": "entrenas?",
            "gym": "Gimnasio",
            "home": "Casa",
            "both": "Ambos",
            "fullEquipment": "Acceso completo a equipos",
            "bodyweightMinimal": "Peso corporal y equipo mínimo",
            "mixGymHome": "Mezcla de gimnasio y casa",
            "availableEquipment": "Equipo disponible",
            "dumbbells": "Mancuernas",
            "pullUpBar": "Barra de dominadas",
            "bodyweightOnly": "Solo peso corporal",
            "primary": "Objetivo",
            "goal": "Principal",
            "whatsYourFocus": "¿Cuál es tu enfoque #1?",
            "buildMuscle": "Ganar músculo",
            "loseFat": "Perder grasa",
            "recomp": "Recomposición",
            "gainSizeStrength": "Ganar tamaño y fuerza",
            "leanDownCut": "Reducir grasa corporal",
            "buildMuscleLoseFat": "Ganar músculo y perder grasa",
            "whatsHolding": "¿Qué te",
            "youBack": "detiene?",
            "selectAllApply": "Selecciona todo lo que aplique",
            "lackMotivation": "Falta de motivación",
            "noWorkoutPlan": "Sin plan de entrenamiento",
            "poorNutrition": "Mala nutrición",
            "inconsistency": "Inconsistencia",
            "timeManagement": "Gestión del tiempo",
            "injuriesPain": "Lesiones o dolor",
            "lowEnergy": "Baja energía",
            "notSeeingResults": "No ver resultados",
            "gymIntimidation": "Intimidación en el gym",
            "dontKnowStart": "No sé por dónde empezar",
            "in90Days": "En 90 días,",
            "iWantTo": "Quiero...",
            "chooseTopGoals": "Elige tus objetivos principales",
            "buildMuscleGoal": "Ganar músculo",
            "loseFatGoal": "Perder grasa",
            "getStronger": "Ser más fuerte",
            "improveEndurance": "Mejorar resistencia",
            "betterPosture": "Mejor postura",
            "increaseFlexibility": "Aumentar flexibilidad",
            "runMarathon": "Correr un maratón",
            "feelConfident": "Sentirme más seguro",
            "buildRoutine": "Crear una rutina",
            "competeInFitness": "Competir en fitness",
            "trainingConfidence": "Confianza en el",
            "confidence": "Entrenamiento",
            "howExperienced": "¿Qué tan experimentado eres?",
            "justGettingStarted": "Empezando",
            "knowBasicsWell": "Conozco lo básico",
            "yearsOfExperience": "Años de experiencia",
            "competitiveAthleteLevel": "Nivel de atleta competitivo",
            "whenWere": "¿Cuándo",
            "youBorn": "naciste?",
            "helpsPersonalize": "Esto nos ayuda a personalizar tu plan",
            "yearsOld": "años",
            "yourBody": "Tus Medidas",
            "measurements": "Corporales",
            "height": "ALTURA",
            "weight": "PESO",
            "imperial": "Imperial",
            "metric": "Métrico",
            "referralCode": "Código de referido",
            "gotCodeFriend": "¿Tienes un código de un amigo? Ingrésalo abajo.",
            "enterCode": "Ingresar código",
            "codeEntered": "Código ingresado",
            "applyAndContinue": "Aplicar y continuar",
            "noCode": "No tengo código",
            "fitAICreates": "Fit AI crea",
            "longTermResults": "resultados a largo plazo",
            "yourPhysique": "Tu Físico",
            "month1": "Mes 1",
            "month6": "Mes 6",
            "fitAITraining": "Entrenamiento Fit AI",
            "traditionalTraining": "Entrenamiento Tradicional",
            "usersMainGains": "El 80% de los usuarios de Fit AI mantienen\nsus ganancias físicas 6 meses después",
            "spinToWin": "Gira para ganar",
            "getExclusiveDiscount": "Obtén un descuento exclusivo",
            "spinTheWheel": "Gira la ruleta",
            "noThanks": "No gracias",
            "unlockFitAIPro": "Desbloquea Fit AI Pro",
            "premiumExperience": "Tu experiencia fitness premium con IA",
            "startFreeTrial": "Iniciar prueba gratuita de 3 días",
            "cancelAnytime": "Cancela en cualquier momento.",
            "latestScore": "Última puntuación",
            "noScanYet": "Sin escaneo aún",
            "readyToScan": "Listo para escanear",
            "uploadPhotos": "Sube tus fotos para análisis con IA",
            "front": "Frontal",
            "back": "Espalda",
            "optional": "Opcional",
            "analyzing": "Analizando...",
            "analyzeWithAI": "Analizar con IA",
            "pro": "(Pro)",
            "photoGuidelines": "Guía de fotos",
            "tipsForBetterScan": "Consejos para un mejor escaneo",
            "goodLighting": "Buena iluminación",
            "neutralPose": "Postura neutra de pie",
            "torsoVisible": "Torso o cuerpo completo visible",
            "plainBackground": "Fondo liso si es posible",
            "ninetyDayTransformation": "Transformación 90 días",
            "seePotentialPhysique": "Ve tu potencial físico con IA",
            "tapToViewFull": "Toca para ver completo",
            "generating": "Generando...",
            "regenerate": "Regenerar",
            "generatePreview": "Generar vista previa",
            "results": "Resultados",
            "strengths": "Fortalezas",
            "areasToImprove": "Áreas a mejorar",
            "summary": "Resumen",
            "recommendations": "Recomendaciones",
            "potential": "Potencial",
            "muscleMass": "Masa Muscular",
            "ratings": "Calificaciones",
            "saved": "Guardado",
            "share": "Compartir",
            "excellent": "Excelente",
            "great": "Genial",
            "good": "Bien",
            "average": "Promedio",
            "needsWork": "Necesita trabajo",
            "transformation": "Transformación",
            "your90DayPotential": "Tu potencial en 90 días",
            "generatingTransformation": "Generando tu transformación de 90 días...",
            "mayTakeMinute": "Puede tomar hasta un minuto",
            "couldNotGenerate": "No se pudo generar la transformación",
            "takePhoto": "Tomar foto",
            "chooseFromLibrary": "Elegir de la galería",
            "yourPlanBasedOn": "Tu plan se basa en",
            "todaysGoal": "META DE HOY",
            "restAndRecover": "Descanso y recuperación",
            "startWorkout": "Iniciar entrenamiento",
            "xpReward": "Recompensa XP",
            "target": "Objetivo",
            "weeklyStreak": "Racha semanal",
            "perfectWeek": "¡Semana perfecta!",
            "scanInsight": "Info del escaneo",
            "focusOn": "Enfocarse en",
            "lookingStrong": "se ve fuerte",
            "score": "Puntuación",
            "onTrack": "En camino",
            "scanOverdue": "Escaneo vencido",
            "scanToPersonalize": "Escanea para personalizar",
            "completeScanForPlan": "Haz un escaneo corporal para obtener un plan\nadaptado a tus puntos débiles",
            "focusAreas": "Áreas de enfoque",
            "thisWeek": "Esta semana",
            "competeBonus": "Bonus de competencia",
            "points": "Puntos",
            "streak": "Racha",
            "rank": "Rango",
            "timeForNewScan": "¡Hora de un nuevo escaneo!",
            "keepConsistent": "Mantén la consistencia",
            "completeFirstScan": "Completa tu primer escaneo",
            "trackProgress": "Sigue tu progreso con escaneos",
            "workouts": "Entrenamientos",
            "dayStreak": "Días seguidos",
            "xpEarned": "XP ganado",
            "improvementAreas": "Áreas de mejora",
            "doneLabel": "HECHO",
            "focusLabel": "FOCO",
            "xp": "XP",
            "wins": "victorias",
            "season": "TEMPORADA",
            "daysRemaining": "días restantes",
            "ends": "TERMINA",
            "activeChallenge": "RETO ACTIVO",
            "weeklyWarrior": "Guerrero Semanal",
            "physiqueBattle": "Batalla de Físicos 1v1",
            "you": "TÚ",
            "vs": "VS",
            "week": "Semana",
            "train": "Entrenar",
            "move": "Mover",
            "challenges": "Retos",
            "showLess": "Mostrar menos",
            "leaderboard": "Clasificación",
            "achievements": "Logros",
            "activity": "Actividad",
            "recent": "Reciente",
            "aiCoach": "Coach IA",
            "yourAICoach": "Tu Coach IA",
            "askAnythingFitness": "Pregúntame sobre fitness, nutrición,\nrecuperación o tu plan de entrenamiento.",
            "tryAsking": "Intenta preguntar",
            "askYourCoach": "Pregunta a tu coach...",
            "settings": "Configuración",
            "notifications": "Notificaciones",
            "darkMode": "Modo oscuro",
            "appleHealth": "Apple Health",
            "language": "Idioma",
            "restorePurchases": "Restaurar compras",
            "termsPrivacy": "Términos y privacidad",
            "scanHistory": "Historial de escaneos",
            "noScansYet": "Sin escaneos aún",
            "comingSoon": "Próximamente",
            "comingSoonMessage": "Esta función estará disponible pronto.",
            "editProfile": "Editar perfil",
            "scans": "Escaneos",
            "limitedOffer": "Oferta limitada",
            "name": "Nombre",
            "shortBio": "Bio corta (opcional)",
            "removePhoto": "Eliminar foto",
            "monthly": "Mensual",
            "annual": "Anual",
            "lifetime": "Vitalicio",
            "perMonth": "/mes",
            "perYear": "/año",
            "oneTime": "único pago",
            "bestValue": "MEJOR VALOR",
            "streakDaysCount": "Racha: %@ días",
            "toNextTier": "para %@",
            "focusOnArea": "Enfocarse en %@",
            "lookingStrongArea": "%@ se ve fuerte",
            "scannedDaysAgo": "Escaneado hace %@ días",
            "consistencyPercent": "Consistencia: %@%%",
            "completeForPointsMsg": "Completa %@ para ganar +%@ puntos",
            "timesPerWeek": "%@x/semana",
            "hard": "Difícil",
            "easy": "Fácil",
            "exercises": "Ejercicios",
            "totalSets": "Series totales",
            "estTime": "Tiempo est.",
            "completedStatus": "Completado",
            "inProgressStatus": "En progreso",
            "completeWorkout": "Completar entrenamiento",
            "finishEarly": "Terminar antes",
            "tips": "Consejos",
            "workoutCompleteTitle": "¡Entrenamiento completado!",
            "finishButton": "Terminar",
            "workoutCompleteMsg": "Completaste %@/%@ ejercicios en %@ minutos. +%@ puntos!",
            "setsLabel": "series",
            "currentScore": "Puntuación actual",
            "whyThisMatters": "Por qué importa",
            "recommendedExercises": "Ejercicios recomendados",
            "highPriority": "Alta prioridad",
            "moderateLabel": "Moderado",
            "maintainingLabel": "Mantenimiento",
            "oneVOneBattle": "Batalla 1v1",
            "opponentLabel": "Oponente",
            "battleDesc": "Sube ambas fotos y deja que la IA decida quién gana",
            "opponentNameLabel": "Nombre del oponente",
            "enterNamePlaceholder": "Ingresa nombre",
            "addPhoto": "Añadir foto",
            "startBattle": "Iniciar batalla",
            "physiqueBattleHeader": "BATALLA DE FÍSICOS",
            "moggedStamp": "MOGGED",
            "overallScoreLabel": "Puntuación general",
            "muscleBreakdown": "Desglose muscular",
            "shareBattleCard": "Compartir tarjeta",
            "winsBy": "¡%@ gana por %@ puntos!",
            "shareBattle": "Compartir batalla",
            "overallLabel": "General",
            "tipRest": "Descansa 60-90s entre series para hipertrofia",
            "tipEccentric": "Enfócate en la fase excéntrica controlada",
            "tipHydration": "Mantente hidratado entre series",
            "tipWeakPoints": "Más volumen en puntos débiles acelera el crecimiento",
            "youLabel": "(Tú)",
            "todayLabel": "hoy",
            "xpToNextTier": "%@ XP para %@",
            "focusBadge": "FOCO",
            "doneBadge": "HECHO",
            "winterBulk": "Volumen Invernal",
            "springCut": "Corte Primavera",
            "summerShred": "Definición Verano",
            "fallGains": "Ganancias Otoño",
        ],

        "French": [
            "getStarted": "Commencer",
            "continue": "Continuer",
            "next": "Suivant",
            "save": "Enregistrer",
            "cancel": "Annuler",
            "done": "Terminé",
            "close": "Fermer",
            "logIn": "Se connecter",
            "logOut": "Déconnexion",
            "alreadyHaveAccount": "Vous avez déjà un compte?",
            "scan": "Scanner",
            "plan": "Programme",
            "compete": "Compétition",
            "profile": "Profil",
            "ok": "OK",
            "yourPersonalCoach": "Votre coach fitness\nIA personnel.",
            "scanPlanCompete": "Scannez, planifiez et compétez.",
            "byContinuingAgree": "En continuant vous acceptez nos",
            "terms": "Conditions",
            "and": "et",
            "privacyPolicy": "Politique de confidentialité",
            "signIn": "Se connecter",
            "signInGoogle": "Se connecter avec Google",
            "continueEmail": "Continuer avec email",
            "byContinuingFitAI": "En continuant vous acceptez les",
            "termsAndConditions": "Conditions générales",
            "whatsYourGender": "Quel est votre",
            "gender": "genre?",
            "male": "Homme",
            "female": "Femme",
            "gymRat": "GymRat",
            "howManyTimes": "Combien de fois",
            "perWeek": "par semaine?",
            "howOftenTrain": "À quelle fréquence voulez-vous vous entraîner?",
            "training": "Expérience",
            "experience": "d'Entraînement",
            "howLongTraining": "Depuis combien de temps vous entraînez-vous?",
            "beginner": "Débutant",
            "intermediate": "Intermédiaire",
            "advanced": "Avancé",
            "expert": "Expert",
            "lessThan6Months": "Moins de 6 mois",
            "sixMonthsTo2Years": "6 mois – 2 ans",
            "twoYearsPlus": "Plus de 2 ans",
            "competitiveLevel": "Niveau compétitif",
            "whereDoYou": "Où vous",
            "youTrain": "entraînez-vous?",
            "gym": "Salle de sport",
            "home": "Maison",
            "both": "Les deux",
            "fullEquipment": "Accès complet aux équipements",
            "bodyweightMinimal": "Poids du corps et équipement minimal",
            "mixGymHome": "Mélange salle et maison",
            "primary": "Objectif",
            "goal": "Principal",
            "whatsYourFocus": "Quel est votre objectif #1?",
            "buildMuscle": "Gagner du muscle",
            "loseFat": "Perdre du gras",
            "recomp": "Recomposition",
            "gainSizeStrength": "Gagner en taille et force",
            "leanDownCut": "Réduire la masse grasse",
            "buildMuscleLoseFat": "Gagner du muscle et perdre du gras",
            "whatsHolding": "Qu'est-ce qui",
            "youBack": "vous retient?",
            "selectAllApply": "Sélectionnez tout ce qui s'applique",
            "in90Days": "Dans 90 jours,",
            "iWantTo": "Je veux...",
            "chooseTopGoals": "Choisissez vos objectifs",
            "trainingConfidence": "Confiance en",
            "confidence": "l'Entraînement",
            "howExperienced": "Quel est votre niveau?",
            "whenWere": "Quand êtes-vous",
            "youBorn": "né?",
            "helpsPersonalize": "Cela nous aide à personnaliser votre plan",
            "yearsOld": "ans",
            "yourBody": "Vos",
            "measurements": "Mensurations",
            "height": "TAILLE",
            "weight": "POIDS",
            "imperial": "Impérial",
            "metric": "Métrique",
            "referralCode": "Code de parrainage",
            "gotCodeFriend": "Vous avez un code d'un ami? Entrez-le ci-dessous.",
            "enterCode": "Entrer le code",
            "codeEntered": "Code entré",
            "applyAndContinue": "Appliquer et continuer",
            "noCode": "Je n'ai pas de code",
            "fitAICreates": "Fit AI crée",
            "longTermResults": "des résultats durables",
            "yourPhysique": "Votre Physique",
            "month1": "Mois 1",
            "month6": "Mois 6",
            "fitAITraining": "Entraînement Fit AI",
            "traditionalTraining": "Entraînement Traditionnel",
            "usersMainGains": "80% des utilisateurs de Fit AI maintiennent\nleurs gains physiques 6 mois après",
            "spinToWin": "Tournez pour gagner",
            "getExclusiveDiscount": "Obtenez une remise exclusive",
            "spinTheWheel": "Tourner la roue",
            "noThanks": "Non merci",
            "unlockFitAIPro": "Débloquez Fit AI Pro",
            "premiumExperience": "Votre expérience fitness premium avec IA",
            "startFreeTrial": "Démarrer l'essai gratuit de 3 jours",
            "cancelAnytime": "Annulez à tout moment.",
            "latestScore": "Dernier score",
            "noScanYet": "Pas encore de scan",
            "readyToScan": "Prêt à scanner",
            "uploadPhotos": "Téléchargez vos photos pour l'analyse IA",
            "front": "Face",
            "back": "Dos",
            "optional": "Optionnel",
            "analyzing": "Analyse en cours...",
            "analyzeWithAI": "Analyser avec l'IA",
            "pro": "(Pro)",
            "tipsForBetterScan": "Conseils pour un meilleur scan",
            "goodLighting": "Bon éclairage uniforme",
            "neutralPose": "Posture neutre debout",
            "torsoVisible": "Torse ou corps complet visible",
            "plainBackground": "Fond uni si possible",
            "ninetyDayTransformation": "Transformation 90 jours",
            "generating": "Génération...",
            "regenerate": "Régénérer",
            "generatePreview": "Générer l'aperçu",
            "results": "Résultats",
            "strengths": "Points forts",
            "areasToImprove": "Axes d'amélioration",
            "summary": "Résumé",
            "recommendations": "Recommandations",
            "potential": "Potentiel",
            "muscleMass": "Masse Musculaire",
            "ratings": "Notes",
            "saved": "Enregistré",
            "share": "Partager",
            "excellent": "Excellent",
            "great": "Très bien",
            "good": "Bien",
            "average": "Moyen",
            "needsWork": "À améliorer",
            "transformation": "Transformation",
            "your90DayPotential": "Votre potentiel en 90 jours",
            "takePhoto": "Prendre une photo",
            "chooseFromLibrary": "Choisir dans la bibliothèque",
            "yourPlanBasedOn": "Votre plan est basé sur",
            "todaysGoal": "OBJECTIF DU JOUR",
            "restAndRecover": "Repos et récupération",
            "startWorkout": "Démarrer l'entraînement",
            "weeklyStreak": "Série hebdomadaire",
            "perfectWeek": "Semaine parfaite!",
            "scanInsight": "Aperçu du scan",
            "focusAreas": "Zones à cibler",
            "thisWeek": "Cette semaine",
            "competeBonus": "Bonus compétition",
            "points": "Points",
            "streak": "Série",
            "rank": "Rang",
            "workouts": "Entraînements",
            "dayStreak": "Jours consécutifs",
            "xpEarned": "XP gagné",
            "xp": "XP",
            "wins": "victoires",
            "challenges": "Défis",
            "showLess": "Afficher moins",
            "leaderboard": "Classement",
            "achievements": "Succès",
            "activity": "Activité",
            "recent": "Récent",
            "aiCoach": "Coach IA",
            "yourAICoach": "Votre Coach IA",
            "askYourCoach": "Posez votre question...",
            "tryAsking": "Essayez de demander",
            "settings": "Paramètres",
            "notifications": "Notifications",
            "darkMode": "Mode sombre",
            "appleHealth": "Apple Health",
            "language": "Langue",
            "restorePurchases": "Restaurer les achats",
            "termsPrivacy": "Conditions et confidentialité",
            "scanHistory": "Historique des scans",
            "noScansYet": "Aucun scan",
            "comingSoon": "Bientôt disponible",
            "comingSoonMessage": "Cette fonctionnalité sera bientôt disponible.",
            "editProfile": "Modifier le profil",
            "scans": "Scans",
            "limitedOffer": "Offre limitée",
            "name": "Nom",
            "shortBio": "Bio courte (optionnel)",
            "removePhoto": "Supprimer la photo",
            "monthly": "Mensuel",
            "annual": "Annuel",
            "lifetime": "À vie",
            "streakDaysCount": "Série: %@ jours",
            "toNextTier": "pour %@",
            "focusOnArea": "Se concentrer sur %@",
            "lookingStrongArea": "%@ a l'air fort",
            "scannedDaysAgo": "Scanné il y a %@ jours",
            "consistencyPercent": "Régularité: %@%%",
            "completeForPointsMsg": "Terminez %@ pour gagner +%@ points",
            "timesPerWeek": "%@x/semaine",
            "hard": "Difficile",
            "easy": "Facile",
            "exercises": "Exercices",
            "totalSets": "Séries totales",
            "estTime": "Temps est.",
            "completedStatus": "Terminé",
            "inProgressStatus": "En cours",
            "completeWorkout": "Terminer l'entraînement",
            "finishEarly": "Terminer tôt",
            "tips": "Conseils",
            "workoutCompleteTitle": "Entraînement terminé!",
            "finishButton": "Terminer",
            "workoutCompleteMsg": "Vous avez terminé %@/%@ exercices en %@ minutes. +%@ points!",
            "setsLabel": "séries",
            "currentScore": "Score actuel",
            "whyThisMatters": "Pourquoi c'est important",
            "recommendedExercises": "Exercices recommandés",
            "highPriority": "Haute priorité",
            "moderateLabel": "Modéré",
            "maintainingLabel": "Maintien",
            "oneVOneBattle": "Combat 1v1",
            "opponentLabel": "Adversaire",
            "battleDesc": "Téléchargez les deux photos et laissez l'IA décider",
            "opponentNameLabel": "Nom de l'adversaire",
            "enterNamePlaceholder": "Entrer le nom",
            "addPhoto": "Ajouter photo",
            "startBattle": "Lancer le combat",
            "physiqueBattleHeader": "COMBAT PHYSIQUE",
            "moggedStamp": "MOGGED",
            "overallScoreLabel": "Score global",
            "muscleBreakdown": "Détail musculaire",
            "shareBattleCard": "Partager la carte",
            "winsBy": "%@ gagne par %@ points!",
            "shareBattle": "Partager le combat",
            "overallLabel": "Global",
            "tipRest": "Repos 60-90s entre les séries pour l'hypertrophie",
            "tipEccentric": "Concentrez-vous sur la phase excentrique contrôlée",
            "tipHydration": "Restez hydraté entre les séries",
            "tipWeakPoints": "Plus de volume sur les points faibles accélère la croissance",
            "youLabel": "(Vous)",
            "todayLabel": "aujourd'hui",
            "xpToNextTier": "%@ XP pour %@",
            "focusBadge": "FOCUS",
            "doneBadge": "FAIT",
            "winterBulk": "Volume Hivernal",
            "springCut": "Sèche Printemps",
            "summerShred": "Définition Été",
            "fallGains": "Gains Automne",
        ],

        "German": [
            "getStarted": "Loslegen",
            "continue": "Weiter",
            "next": "Nächste",
            "save": "Speichern",
            "cancel": "Abbrechen",
            "done": "Fertig",
            "close": "Schließen",
            "logIn": "Anmelden",
            "logOut": "Abmelden",
            "alreadyHaveAccount": "Bereits ein Konto?",
            "scan": "Scannen",
            "plan": "Plan",
            "compete": "Wettkampf",
            "profile": "Profil",
            "ok": "OK",
            "yourPersonalCoach": "Dein persönlicher\nKI-Fitness-Coach.",
            "scanPlanCompete": "Scannen, planen und wetteifern.",
            "signIn": "Anmelden",
            "signInGoogle": "Mit Google anmelden",
            "continueEmail": "Mit E-Mail fortfahren",
            "whatsYourGender": "Was ist dein",
            "gender": "Geschlecht?",
            "male": "Männlich",
            "female": "Weiblich",
            "gymRat": "GymRat",
            "howManyTimes": "Wie oft",
            "perWeek": "pro Woche?",
            "howOftenTrain": "Wie oft möchtest du trainieren?",
            "training": "Trainings-",
            "experience": "erfahrung",
            "howLongTraining": "Wie lange trainierst du schon?",
            "beginner": "Anfänger",
            "intermediate": "Fortgeschritten",
            "advanced": "Erfahren",
            "expert": "Experte",
            "lessThan6Months": "Weniger als 6 Monate",
            "sixMonthsTo2Years": "6 Monate – 2 Jahre",
            "twoYearsPlus": "Über 2 Jahre Training",
            "competitiveLevel": "Wettkampfniveau",
            "whereDoYou": "Wo",
            "youTrain": "trainierst du?",
            "gym": "Fitnessstudio",
            "home": "Zuhause",
            "both": "Beides",
            "primary": "Haupt-",
            "goal": "ziel",
            "whatsYourFocus": "Was ist dein Fokus #1?",
            "buildMuscle": "Muskeln aufbauen",
            "loseFat": "Fett verlieren",
            "recomp": "Rekomposition",
            "whatsHolding": "Was hält",
            "youBack": "dich zurück?",
            "selectAllApply": "Alles Zutreffende auswählen",
            "in90Days": "In 90 Tagen,",
            "iWantTo": "möchte ich...",
            "chooseTopGoals": "Wähle deine Top-Ziele",
            "trainingConfidence": "Trainings-",
            "confidence": "vertrauen",
            "howExperienced": "Wie erfahren bist du?",
            "whenWere": "Wann bist du",
            "youBorn": "geboren?",
            "helpsPersonalize": "Das hilft uns, deinen Plan zu personalisieren",
            "yearsOld": "Jahre alt",
            "yourBody": "Deine",
            "measurements": "Körpermaße",
            "height": "GRÖßE",
            "weight": "GEWICHT",
            "imperial": "Imperial",
            "metric": "Metrisch",
            "referralCode": "Empfehlungscode",
            "gotCodeFriend": "Hast du einen Code von einem Freund? Gib ihn unten ein.",
            "enterCode": "Code eingeben",
            "codeEntered": "Code eingegeben",
            "applyAndContinue": "Anwenden und weiter",
            "noCode": "Ich habe keinen Code",
            "fitAICreates": "Fit AI erzielt",
            "longTermResults": "langfristige Ergebnisse",
            "yourPhysique": "Dein Körper",
            "month1": "Monat 1",
            "month6": "Monat 6",
            "fitAITraining": "Fit AI Training",
            "traditionalTraining": "Traditionelles Training",
            "latestScore": "Letzter Score",
            "noScanYet": "Noch kein Scan",
            "readyToScan": "Bereit zum Scannen",
            "uploadPhotos": "Lade deine Fotos für die KI-Analyse hoch",
            "front": "Vorne",
            "back": "Hinten",
            "optional": "Optional",
            "analyzing": "Analysiere...",
            "analyzeWithAI": "Mit KI analysieren",
            "tipsForBetterScan": "Tipps für einen besseren Scan",
            "results": "Ergebnisse",
            "strengths": "Stärken",
            "areasToImprove": "Verbesserungsbereiche",
            "summary": "Zusammenfassung",
            "recommendations": "Empfehlungen",
            "share": "Teilen",
            "saved": "Gespeichert",
            "todaysGoal": "HEUTIGES ZIEL",
            "restAndRecover": "Ruhe & Erholung",
            "startWorkout": "Training starten",
            "weeklyStreak": "Wöchentliche Serie",
            "thisWeek": "Diese Woche",
            "points": "Punkte",
            "streak": "Serie",
            "rank": "Rang",
            "workouts": "Trainings",
            "challenges": "Herausforderungen",
            "leaderboard": "Rangliste",
            "achievements": "Erfolge",
            "activity": "Aktivität",
            "recent": "Neueste",
            "aiCoach": "KI Coach",
            "yourAICoach": "Dein KI Coach",
            "askYourCoach": "Frag deinen Coach...",
            "tryAsking": "Versuch zu fragen",
            "settings": "Einstellungen",
            "notifications": "Benachrichtigungen",
            "darkMode": "Dunkelmodus",
            "language": "Sprache",
            "restorePurchases": "Käufe wiederherstellen",
            "termsPrivacy": "AGB & Datenschutz",
            "scanHistory": "Scan-Verlauf",
            "noScansYet": "Noch keine Scans",
            "comingSoon": "Demnächst",
            "comingSoonMessage": "Diese Funktion kommt bald.",
            "editProfile": "Profil bearbeiten",
            "scans": "Scans",
            "name": "Name",
            "removePhoto": "Foto entfernen",
            "streakDaysCount": "Serie: %@ Tage",
            "toNextTier": "bis %@",
            "focusOnArea": "Fokus auf %@",
            "lookingStrongArea": "%@ sieht stark aus",
            "scannedDaysAgo": "Vor %@ Tagen gescannt",
            "consistencyPercent": "Konsistenz: %@%%",
            "completeForPointsMsg": "Schließe %@ ab für +%@ Punkte",
            "timesPerWeek": "%@x/Woche",
            "hard": "Schwer",
            "easy": "Leicht",
            "exercises": "Übungen",
            "totalSets": "Gesamte Sätze",
            "estTime": "Gesch. Zeit",
            "completedStatus": "Abgeschlossen",
            "inProgressStatus": "Läuft",
            "completeWorkout": "Training abschließen",
            "finishEarly": "Früher beenden",
            "tips": "Tipps",
            "workoutCompleteTitle": "Training abgeschlossen!",
            "finishButton": "Fertig",
            "workoutCompleteMsg": "Du hast %@/%@ Übungen in %@ Minuten abgeschlossen. +%@ Punkte!",
            "setsLabel": "Sätze",
            "currentScore": "Aktueller Score",
            "whyThisMatters": "Warum das wichtig ist",
            "recommendedExercises": "Empfohlene Übungen",
            "highPriority": "Hohe Priorität",
            "moderateLabel": "Mittel",
            "maintainingLabel": "Beibehalten",
            "oneVOneBattle": "1v1 Kampf",
            "opponentLabel": "Gegner",
            "battleDesc": "Lade beide Fotos hoch und lass die KI entscheiden",
            "opponentNameLabel": "Name des Gegners",
            "enterNamePlaceholder": "Name eingeben",
            "addPhoto": "Foto hinzufügen",
            "startBattle": "Kampf starten",
            "physiqueBattleHeader": "PHYSIQUE KAMPF",
            "moggedStamp": "MOGGED",
            "overallScoreLabel": "Gesamtbewertung",
            "muscleBreakdown": "Muskelaufschlüsselung",
            "shareBattleCard": "Karte teilen",
            "winsBy": "%@ gewinnt mit %@ Punkten!",
            "shareBattle": "Kampf teilen",
            "overallLabel": "Gesamt",
            "tipRest": "60-90s Pause zwischen Sätzen für Hypertrophie",
            "tipEccentric": "Fokus auf kontrollierte exzentrische Phase",
            "tipHydration": "Bleib hydriert zwischen den Sätzen",
            "tipWeakPoints": "Mehr Volumen bei Schwachstellen beschleunigt das Wachstum",
            "youLabel": "(Du)",
            "todayLabel": "heute",
            "xpToNextTier": "%@ XP bis %@",
            "focusBadge": "FOKUS",
            "doneBadge": "FERTIG",
            "winterBulk": "Winter Aufbau",
            "springCut": "Frühling Diät",
            "summerShred": "Sommer Definition",
            "fallGains": "Herbst Gains",
        ],

        "Portuguese": [
            "getStarted": "Começar",
            "continue": "Continuar",
            "next": "Próximo",
            "save": "Salvar",
            "cancel": "Cancelar",
            "done": "Pronto",
            "close": "Fechar",
            "logIn": "Entrar",
            "logOut": "Sair",
            "alreadyHaveAccount": "Já tem uma conta?",
            "scan": "Escanear",
            "plan": "Plano",
            "compete": "Competir",
            "profile": "Perfil",
            "ok": "OK",
            "yourPersonalCoach": "Seu treinador pessoal\nde IA.",
            "scanPlanCompete": "Escaneie, planeje e compita.",
            "signIn": "Entrar",
            "signInGoogle": "Entrar com Google",
            "continueEmail": "Continuar com email",
            "whatsYourGender": "Qual é o seu",
            "gender": "gênero?",
            "male": "Masculino",
            "female": "Feminino",
            "gymRat": "GymRat",
            "howManyTimes": "Quantas vezes",
            "perWeek": "por semana?",
            "howOftenTrain": "Com que frequência quer treinar?",
            "training": "Experiência",
            "experience": "de Treino",
            "howLongTraining": "Há quanto tempo você treina?",
            "beginner": "Iniciante",
            "intermediate": "Intermediário",
            "advanced": "Avançado",
            "expert": "Especialista",
            "whereDoYou": "Onde você",
            "youTrain": "treina?",
            "gym": "Academia",
            "home": "Casa",
            "both": "Ambos",
            "primary": "Objetivo",
            "goal": "Principal",
            "whatsYourFocus": "Qual é o seu foco #1?",
            "buildMuscle": "Ganhar músculo",
            "loseFat": "Perder gordura",
            "recomp": "Recomposição",
            "whatsHolding": "O que te",
            "youBack": "impede?",
            "selectAllApply": "Selecione tudo que se aplica",
            "in90Days": "Em 90 dias,",
            "iWantTo": "Eu quero...",
            "chooseTopGoals": "Escolha seus objetivos",
            "trainingConfidence": "Confiança no",
            "confidence": "Treino",
            "howExperienced": "Qual seu nível?",
            "whenWere": "Quando você",
            "youBorn": "nasceu?",
            "yearsOld": "anos",
            "yourBody": "Suas Medidas",
            "measurements": "Corporais",
            "height": "ALTURA",
            "weight": "PESO",
            "referralCode": "Código de indicação",
            "fitAICreates": "Fit AI cria",
            "longTermResults": "resultados a longo prazo",
            "latestScore": "Última pontuação",
            "readyToScan": "Pronto para escanear",
            "front": "Frente",
            "back": "Costas",
            "analyzing": "Analisando...",
            "analyzeWithAI": "Analisar com IA",
            "results": "Resultados",
            "strengths": "Pontos fortes",
            "areasToImprove": "Áreas a melhorar",
            "summary": "Resumo",
            "recommendations": "Recomendações",
            "share": "Compartilhar",
            "saved": "Salvo",
            "todaysGoal": "META DE HOJE",
            "startWorkout": "Iniciar treino",
            "weeklyStreak": "Sequência semanal",
            "thisWeek": "Esta semana",
            "points": "Pontos",
            "streak": "Sequência",
            "workouts": "Treinos",
            "challenges": "Desafios",
            "leaderboard": "Classificação",
            "achievements": "Conquistas",
            "activity": "Atividade",
            "aiCoach": "Coach IA",
            "yourAICoach": "Seu Coach IA",
            "askYourCoach": "Pergunte ao seu coach...",
            "settings": "Configurações",
            "notifications": "Notificações",
            "darkMode": "Modo escuro",
            "language": "Idioma",
            "restorePurchases": "Restaurar compras",
            "termsPrivacy": "Termos e privacidade",
            "scanHistory": "Histórico de scans",
            "noScansYet": "Nenhum scan ainda",
            "comingSoon": "Em breve",
            "comingSoonMessage": "Este recurso estará disponível em breve.",
            "editProfile": "Editar perfil",
            "scans": "Scans",
        ],

        "Italian": [
            "getStarted": "Inizia",
            "continue": "Continua",
            "next": "Avanti",
            "save": "Salva",
            "cancel": "Annulla",
            "done": "Fatto",
            "close": "Chiudi",
            "logIn": "Accedi",
            "logOut": "Esci",
            "alreadyHaveAccount": "Hai già un account?",
            "scan": "Scansione",
            "plan": "Piano",
            "compete": "Competi",
            "profile": "Profilo",
            "ok": "OK",
            "yourPersonalCoach": "Il tuo coach fitness\nIA personale.",
            "scanPlanCompete": "Scansiona, pianifica e competi.",
            "signIn": "Accedi",
            "signInGoogle": "Accedi con Google",
            "continueEmail": "Continua con email",
            "whatsYourGender": "Qual è il tuo",
            "gender": "genere?",
            "male": "Maschio",
            "female": "Femmina",
            "gymRat": "GymRat",
            "howManyTimes": "Quante volte",
            "perWeek": "a settimana?",
            "howOftenTrain": "Quanto spesso vuoi allenarti?",
            "training": "Esperienza di",
            "experience": "Allenamento",
            "howLongTraining": "Da quanto tempo ti alleni?",
            "beginner": "Principiante",
            "intermediate": "Intermedio",
            "advanced": "Avanzato",
            "expert": "Esperto",
            "whereDoYou": "Dove ti",
            "youTrain": "alleni?",
            "gym": "Palestra",
            "home": "Casa",
            "both": "Entrambi",
            "primary": "Obiettivo",
            "goal": "Principale",
            "whatsYourFocus": "Qual è il tuo focus #1?",
            "buildMuscle": "Aumentare massa",
            "loseFat": "Perdere grasso",
            "recomp": "Ricomposizione",
            "whatsHolding": "Cosa ti",
            "youBack": "trattiene?",
            "selectAllApply": "Seleziona tutto ciò che si applica",
            "in90Days": "In 90 giorni,",
            "iWantTo": "Voglio...",
            "chooseTopGoals": "Scegli i tuoi obiettivi",
            "trainingConfidence": "Fiducia",
            "confidence": "nell'Allenamento",
            "howExperienced": "Qual è il tuo livello?",
            "whenWere": "Quando sei",
            "youBorn": "nato?",
            "yearsOld": "anni",
            "yourBody": "Le tue Misure",
            "measurements": "Corporee",
            "height": "ALTEZZA",
            "weight": "PESO",
            "referralCode": "Codice referral",
            "fitAICreates": "Fit AI crea",
            "longTermResults": "risultati a lungo termine",
            "latestScore": "Ultimo punteggio",
            "readyToScan": "Pronto per la scansione",
            "front": "Fronte",
            "back": "Schiena",
            "analyzing": "Analisi in corso...",
            "analyzeWithAI": "Analizza con l'IA",
            "results": "Risultati",
            "strengths": "Punti di forza",
            "areasToImprove": "Aree da migliorare",
            "summary": "Riepilogo",
            "recommendations": "Raccomandazioni",
            "share": "Condividi",
            "saved": "Salvato",
            "todaysGoal": "OBIETTIVO DI OGGI",
            "startWorkout": "Inizia allenamento",
            "weeklyStreak": "Serie settimanale",
            "thisWeek": "Questa settimana",
            "points": "Punti",
            "streak": "Serie",
            "workouts": "Allenamenti",
            "challenges": "Sfide",
            "leaderboard": "Classifica",
            "achievements": "Traguardi",
            "activity": "Attività",
            "aiCoach": "Coach IA",
            "yourAICoach": "Il tuo Coach IA",
            "askYourCoach": "Chiedi al tuo coach...",
            "settings": "Impostazioni",
            "notifications": "Notifiche",
            "darkMode": "Modalità scura",
            "language": "Lingua",
            "restorePurchases": "Ripristina acquisti",
            "termsPrivacy": "Termini e privacy",
            "scanHistory": "Cronologia scansioni",
            "noScansYet": "Nessuna scansione",
            "comingSoon": "Prossimamente",
            "comingSoonMessage": "Questa funzione sarà disponibile a breve.",
            "editProfile": "Modifica profilo",
            "scans": "Scansioni",
        ],

        "Russian": [
            "getStarted": "Начать",
            "continue": "Продолжить",
            "next": "Далее",
            "save": "Сохранить",
            "cancel": "Отмена",
            "done": "Готово",
            "close": "Закрыть",
            "logIn": "Войти",
            "logOut": "Выйти",
            "alreadyHaveAccount": "Уже есть аккаунт?",
            "scan": "Сканирование",
            "plan": "План",
            "compete": "Соревнование",
            "profile": "Профиль",
            "ok": "OK",
            "yourPersonalCoach": "Ваш персональный\nИИ фитнес-тренер.",
            "scanPlanCompete": "Сканируйте, планируйте и соревнуйтесь.",
            "signIn": "Войти",
            "signInGoogle": "Войти через Google",
            "continueEmail": "Продолжить с email",
            "whatsYourGender": "Ваш",
            "gender": "пол?",
            "male": "Мужской",
            "female": "Женский",
            "gymRat": "GymRat",
            "howManyTimes": "Сколько раз",
            "perWeek": "в неделю?",
            "howOftenTrain": "Как часто вы хотите тренироваться?",
            "training": "Опыт",
            "experience": "тренировок",
            "howLongTraining": "Как давно вы тренируетесь?",
            "beginner": "Новичок",
            "intermediate": "Средний",
            "advanced": "Продвинутый",
            "expert": "Эксперт",
            "whereDoYou": "Где вы",
            "youTrain": "тренируетесь?",
            "gym": "Зал",
            "home": "Дома",
            "both": "Оба варианта",
            "primary": "Главная",
            "goal": "Цель",
            "whatsYourFocus": "Ваш главный фокус?",
            "buildMuscle": "Набрать мышцы",
            "loseFat": "Сжечь жир",
            "whatsHolding": "Что вас",
            "youBack": "сдерживает?",
            "selectAllApply": "Выберите все подходящие",
            "in90Days": "Через 90 дней,",
            "iWantTo": "Я хочу...",
            "trainingConfidence": "Уверенность в",
            "confidence": "тренировках",
            "howExperienced": "Ваш уровень опыта?",
            "whenWere": "Когда вы",
            "youBorn": "родились?",
            "yearsOld": "лет",
            "yourBody": "Ваши",
            "measurements": "параметры тела",
            "height": "РОСТ",
            "weight": "ВЕС",
            "referralCode": "Реферальный код",
            "fitAICreates": "Fit AI создаёт",
            "longTermResults": "долгосрочные результаты",
            "latestScore": "Последний результат",
            "readyToScan": "Готов к сканированию",
            "front": "Спереди",
            "back": "Сзади",
            "analyzing": "Анализ...",
            "analyzeWithAI": "Анализ с ИИ",
            "results": "Результаты",
            "strengths": "Сильные стороны",
            "areasToImprove": "Зоны улучшения",
            "summary": "Итого",
            "recommendations": "Рекомендации",
            "share": "Поделиться",
            "saved": "Сохранено",
            "todaysGoal": "ЦЕЛЬ ДНЯ",
            "startWorkout": "Начать тренировку",
            "weeklyStreak": "Недельная серия",
            "thisWeek": "Эта неделя",
            "points": "Очки",
            "streak": "Серия",
            "workouts": "Тренировки",
            "challenges": "Задачи",
            "leaderboard": "Рейтинг",
            "achievements": "Достижения",
            "activity": "Активность",
            "aiCoach": "ИИ Тренер",
            "yourAICoach": "Ваш ИИ Тренер",
            "askYourCoach": "Спросите тренера...",
            "settings": "Настройки",
            "notifications": "Уведомления",
            "darkMode": "Тёмная тема",
            "language": "Язык",
            "restorePurchases": "Восстановить покупки",
            "termsPrivacy": "Условия и конфиденциальность",
            "scanHistory": "История сканирований",
            "noScansYet": "Нет сканирований",
            "comingSoon": "Скоро",
            "comingSoonMessage": "Эта функция скоро будет доступна.",
            "editProfile": "Редактировать профиль",
            "scans": "Сканирования",
        ],

        "Japanese": [
            "getStarted": "始める",
            "continue": "続ける",
            "next": "次へ",
            "save": "保存",
            "cancel": "キャンセル",
            "done": "完了",
            "close": "閉じる",
            "logIn": "ログイン",
            "logOut": "ログアウト",
            "alreadyHaveAccount": "アカウントをお持ちですか？",
            "scan": "スキャン",
            "plan": "プラン",
            "compete": "競争",
            "profile": "プロフィール",
            "ok": "OK",
            "yourPersonalCoach": "あなた専属のAI\nフィットネスコーチ。",
            "scanPlanCompete": "スキャン、プラン、競争。",
            "signIn": "サインイン",
            "signInGoogle": "Googleでサインイン",
            "whatsYourGender": "あなたの",
            "gender": "性別は？",
            "male": "男性",
            "female": "女性",
            "gymRat": "GymRat",
            "howManyTimes": "週に",
            "perWeek": "何回？",
            "training": "トレーニング",
            "experience": "経験",
            "beginner": "初心者",
            "intermediate": "中級者",
            "advanced": "上級者",
            "expert": "エキスパート",
            "whereDoYou": "どこで",
            "youTrain": "トレーニング？",
            "gym": "ジム",
            "home": "自宅",
            "both": "両方",
            "primary": "メインの",
            "goal": "目標",
            "buildMuscle": "筋肉増強",
            "loseFat": "脂肪燃焼",
            "whatsHolding": "何が",
            "youBack": "障害ですか？",
            "in90Days": "90日後に、",
            "iWantTo": "私は...",
            "trainingConfidence": "トレーニングの",
            "confidence": "自信",
            "whenWere": "いつ",
            "youBorn": "生まれましたか？",
            "yearsOld": "歳",
            "yourBody": "あなたの",
            "measurements": "体の計測値",
            "height": "身長",
            "weight": "体重",
            "referralCode": "紹介コード",
            "fitAICreates": "Fit AIが生み出す",
            "longTermResults": "長期的な結果",
            "latestScore": "最新スコア",
            "readyToScan": "スキャン準備完了",
            "front": "前面",
            "back": "背面",
            "analyzing": "分析中...",
            "analyzeWithAI": "AIで分析",
            "results": "結果",
            "strengths": "強み",
            "areasToImprove": "改善点",
            "summary": "まとめ",
            "recommendations": "おすすめ",
            "share": "共有",
            "saved": "保存済み",
            "todaysGoal": "今日の目標",
            "startWorkout": "トレーニング開始",
            "weeklyStreak": "週間連続",
            "thisWeek": "今週",
            "points": "ポイント",
            "streak": "連続",
            "workouts": "トレーニング",
            "challenges": "チャレンジ",
            "leaderboard": "ランキング",
            "achievements": "実績",
            "activity": "アクティビティ",
            "aiCoach": "AIコーチ",
            "yourAICoach": "あなたのAIコーチ",
            "askYourCoach": "コーチに聞く...",
            "settings": "設定",
            "notifications": "通知",
            "darkMode": "ダークモード",
            "language": "言語",
            "comingSoon": "近日公開",
            "comingSoonMessage": "この機能は近日公開予定です。",
            "editProfile": "プロフィール編集",
            "scans": "スキャン",
        ],

        "Korean": [
            "getStarted": "시작하기",
            "continue": "계속",
            "next": "다음",
            "save": "저장",
            "cancel": "취소",
            "done": "완료",
            "close": "닫기",
            "logIn": "로그인",
            "logOut": "로그아웃",
            "alreadyHaveAccount": "이미 계정이 있으신가요?",
            "scan": "스캔",
            "plan": "플랜",
            "compete": "경쟁",
            "profile": "프로필",
            "ok": "확인",
            "yourPersonalCoach": "당신의 개인 AI\n피트니스 코치.",
            "scanPlanCompete": "스캔, 계획, 경쟁.",
            "signIn": "로그인",
            "whatsYourGender": "당신의",
            "gender": "성별은?",
            "male": "남성",
            "female": "여성",
            "gymRat": "GymRat",
            "howManyTimes": "일주일에",
            "perWeek": "몇 번?",
            "training": "운동",
            "experience": "경험",
            "beginner": "초보자",
            "intermediate": "중급자",
            "advanced": "상급자",
            "expert": "전문가",
            "whereDoYou": "어디서",
            "youTrain": "운동하나요?",
            "gym": "헬스장",
            "home": "홈",
            "both": "모두",
            "primary": "주요",
            "goal": "목표",
            "buildMuscle": "근육 증가",
            "loseFat": "체지방 감소",
            "in90Days": "90일 후,",
            "iWantTo": "나는...",
            "trainingConfidence": "운동",
            "confidence": "자신감",
            "whenWere": "언제",
            "youBorn": "태어났나요?",
            "yearsOld": "세",
            "height": "키",
            "weight": "체중",
            "referralCode": "추천 코드",
            "fitAICreates": "Fit AI가 만드는",
            "longTermResults": "장기적인 결과",
            "latestScore": "최근 점수",
            "readyToScan": "스캔 준비 완료",
            "front": "전면",
            "back": "후면",
            "analyzing": "분석 중...",
            "analyzeWithAI": "AI로 분석",
            "results": "결과",
            "strengths": "강점",
            "areasToImprove": "개선 영역",
            "todaysGoal": "오늘의 목표",
            "startWorkout": "운동 시작",
            "weeklyStreak": "주간 연속",
            "thisWeek": "이번 주",
            "points": "포인트",
            "streak": "연속",
            "workouts": "운동",
            "challenges": "챌린지",
            "leaderboard": "리더보드",
            "achievements": "업적",
            "aiCoach": "AI 코치",
            "yourAICoach": "당신의 AI 코치",
            "askYourCoach": "코치에게 질문...",
            "settings": "설정",
            "notifications": "알림",
            "darkMode": "다크 모드",
            "language": "언어",
            "comingSoon": "곧 출시",
            "comingSoonMessage": "이 기능은 곧 출시됩니다.",
            "editProfile": "프로필 수정",
            "scans": "스캔",
        ],

        "Chinese": [
            "getStarted": "开始",
            "continue": "继续",
            "next": "下一步",
            "save": "保存",
            "cancel": "取消",
            "done": "完成",
            "close": "关闭",
            "logIn": "登录",
            "logOut": "退出",
            "alreadyHaveAccount": "已有账号？",
            "scan": "扫描",
            "plan": "计划",
            "compete": "竞赛",
            "profile": "个人资料",
            "ok": "好的",
            "yourPersonalCoach": "你的私人AI\n健身教练。",
            "scanPlanCompete": "扫描、计划、竞赛。",
            "signIn": "登录",
            "signInGoogle": "使用Google登录",
            "whatsYourGender": "你的",
            "gender": "性别是？",
            "male": "男",
            "female": "女",
            "gymRat": "GymRat",
            "howManyTimes": "每周",
            "perWeek": "几次？",
            "training": "训练",
            "experience": "经验",
            "beginner": "初学者",
            "intermediate": "中级",
            "advanced": "高级",
            "expert": "专家",
            "whereDoYou": "你在",
            "youTrain": "哪里训练？",
            "gym": "健身房",
            "home": "家里",
            "both": "两者",
            "primary": "主要",
            "goal": "目标",
            "buildMuscle": "增肌",
            "loseFat": "减脂",
            "in90Days": "90天后，",
            "iWantTo": "我想...",
            "trainingConfidence": "训练",
            "confidence": "信心",
            "whenWere": "你什么时候",
            "youBorn": "出生的？",
            "yearsOld": "岁",
            "height": "身高",
            "weight": "体重",
            "referralCode": "推荐码",
            "fitAICreates": "Fit AI 创造",
            "longTermResults": "长期效果",
            "latestScore": "最新得分",
            "readyToScan": "准备扫描",
            "front": "正面",
            "back": "背面",
            "analyzing": "分析中...",
            "analyzeWithAI": "AI分析",
            "results": "结果",
            "strengths": "优势",
            "areasToImprove": "改善空间",
            "todaysGoal": "今日目标",
            "startWorkout": "开始训练",
            "weeklyStreak": "周连续",
            "thisWeek": "本周",
            "points": "积分",
            "streak": "连续",
            "workouts": "训练",
            "challenges": "挑战",
            "leaderboard": "排行榜",
            "achievements": "成就",
            "aiCoach": "AI教练",
            "yourAICoach": "你的AI教练",
            "askYourCoach": "问你的教练...",
            "settings": "设置",
            "notifications": "通知",
            "darkMode": "深色模式",
            "language": "语言",
            "comingSoon": "即将推出",
            "comingSoonMessage": "此功能即将推出。",
            "editProfile": "编辑资料",
            "scans": "扫描",
        ],

        "Arabic": [
            "getStarted": "ابدأ",
            "continue": "متابعة",
            "next": "التالي",
            "save": "حفظ",
            "cancel": "إلغاء",
            "done": "تم",
            "close": "إغلاق",
            "logIn": "تسجيل الدخول",
            "logOut": "تسجيل الخروج",
            "alreadyHaveAccount": "لديك حساب بالفعل؟",
            "scan": "مسح",
            "plan": "خطة",
            "compete": "منافسة",
            "profile": "الملف الشخصي",
            "ok": "حسناً",
            "yourPersonalCoach": "مدربك الشخصي\nبالذكاء الاصطناعي.",
            "scanPlanCompete": "امسح، خطط، وتنافس.",
            "signIn": "تسجيل الدخول",
            "whatsYourGender": "ما هو",
            "gender": "جنسك؟",
            "male": "ذكر",
            "female": "أنثى",
            "gymRat": "GymRat",
            "whenWere": "متى",
            "youBorn": "ولدت؟",
            "height": "الطول",
            "weight": "الوزن",
            "referralCode": "رمز الإحالة",
            "settings": "الإعدادات",
            "notifications": "الإشعارات",
            "darkMode": "الوضع الداكن",
            "language": "اللغة",
            "comingSoon": "قريباً",
            "comingSoonMessage": "هذه الميزة قادمة قريباً.",
            "aiCoach": "مدرب IA",
            "latestScore": "آخر نتيجة",
            "readyToScan": "جاهز للمسح",
            "results": "النتائج",
            "todaysGoal": "هدف اليوم",
            "thisWeek": "هذا الأسبوع",
            "points": "نقاط",
            "streak": "سلسلة",
            "workouts": "تمارين",
            "scans": "مسح",
        ],

        "Hindi": [
            "getStarted": "शुरू करें",
            "continue": "जारी रखें",
            "next": "अगला",
            "save": "सहेजें",
            "cancel": "रद्द करें",
            "done": "हो गया",
            "logIn": "लॉग इन",
            "logOut": "लॉग आउट",
            "alreadyHaveAccount": "पहले से अकाउंट है?",
            "scan": "स्कैन",
            "plan": "योजना",
            "compete": "प्रतिस्पर्धा",
            "profile": "प्रोफ़ाइल",
            "ok": "ठीक है",
            "signIn": "साइन इन",
            "whatsYourGender": "आपका",
            "gender": "लिंग क्या है?",
            "male": "पुरुष",
            "female": "महिला",
            "whenWere": "आपका जन्म",
            "youBorn": "कब हुआ?",
            "height": "ऊंचाई",
            "weight": "वजन",
            "referralCode": "रेफरल कोड",
            "settings": "सेटिंग्स",
            "notifications": "सूचनाएं",
            "darkMode": "डार्क मोड",
            "language": "भाषा",
            "comingSoon": "जल्द आ रहा है",
            "comingSoonMessage": "यह सुविधा जल्द ही उपलब्ध होगी।",
            "aiCoach": "AI कोच",
            "latestScore": "नवीनतम स्कोर",
            "results": "परिणाम",
            "todaysGoal": "आज का लक्ष्य",
            "thisWeek": "इस सप्ताह",
            "points": "अंक",
            "workouts": "कसरत",
            "scans": "स्कैन",
        ],

        "Turkish": [
            "getStarted": "Başla",
            "continue": "Devam",
            "next": "İleri",
            "save": "Kaydet",
            "cancel": "İptal",
            "done": "Tamam",
            "close": "Kapat",
            "logIn": "Giriş Yap",
            "logOut": "Çıkış Yap",
            "alreadyHaveAccount": "Zaten hesabın var mı?",
            "scan": "Tarama",
            "plan": "Plan",
            "compete": "Yarış",
            "profile": "Profil",
            "ok": "Tamam",
            "yourPersonalCoach": "Kişisel AI\nfitness koçun.",
            "scanPlanCompete": "Tara, planla ve yarış.",
            "signIn": "Giriş Yap",
            "whatsYourGender": "Senin",
            "gender": "cinsiyetin?",
            "male": "Erkek",
            "female": "Kadın",
            "gymRat": "GymRat",
            "howManyTimes": "Haftada",
            "perWeek": "kaç kez?",
            "training": "Antrenman",
            "experience": "deneyimi",
            "beginner": "Başlangıç",
            "intermediate": "Orta",
            "advanced": "İleri",
            "expert": "Uzman",
            "whereDoYou": "Nerede",
            "youTrain": "antrenman yapıyorsun?",
            "gym": "Spor salonu",
            "home": "Ev",
            "both": "İkisi de",
            "primary": "Ana",
            "goal": "hedef",
            "buildMuscle": "Kas yap",
            "loseFat": "Yağ yak",
            "whenWere": "Ne zaman",
            "youBorn": "doğdun?",
            "yearsOld": "yaşında",
            "height": "BOY",
            "weight": "KİLO",
            "referralCode": "Referans kodu",
            "latestScore": "Son skor",
            "readyToScan": "Taramaya hazır",
            "front": "Ön",
            "back": "Arka",
            "analyzing": "Analiz ediliyor...",
            "analyzeWithAI": "AI ile analiz et",
            "results": "Sonuçlar",
            "todaysGoal": "BUGÜNKÜ HEDEF",
            "startWorkout": "Antrenmana başla",
            "weeklyStreak": "Haftalık seri",
            "thisWeek": "Bu hafta",
            "points": "Puan",
            "streak": "Seri",
            "workouts": "Antrenmanlar",
            "challenges": "Görevler",
            "leaderboard": "Sıralama",
            "achievements": "Başarılar",
            "aiCoach": "AI Koç",
            "yourAICoach": "Senin AI Koçun",
            "askYourCoach": "Koçuna sor...",
            "settings": "Ayarlar",
            "notifications": "Bildirimler",
            "darkMode": "Karanlık mod",
            "language": "Dil",
            "comingSoon": "Yakında",
            "comingSoonMessage": "Bu özellik yakında geliyor.",
            "editProfile": "Profili düzenle",
            "scans": "Taramalar",
        ],

        "Dutch": [
            "getStarted": "Aan de slag",
            "continue": "Doorgaan",
            "next": "Volgende",
            "save": "Opslaan",
            "cancel": "Annuleren",
            "done": "Klaar",
            "logIn": "Inloggen",
            "logOut": "Uitloggen",
            "alreadyHaveAccount": "Al een account?",
            "scan": "Scannen",
            "plan": "Plan",
            "compete": "Competitie",
            "profile": "Profiel",
            "ok": "OK",
            "whatsYourGender": "Wat is je",
            "gender": "geslacht?",
            "male": "Man",
            "female": "Vrouw",
            "whenWere": "Wanneer ben je",
            "youBorn": "geboren?",
            "height": "LENGTE",
            "weight": "GEWICHT",
            "referralCode": "Verwijzingscode",
            "settings": "Instellingen",
            "notifications": "Meldingen",
            "darkMode": "Donkere modus",
            "language": "Taal",
            "comingSoon": "Binnenkort",
            "comingSoonMessage": "Deze functie komt binnenkort.",
            "latestScore": "Laatste score",
            "readyToScan": "Klaar om te scannen",
            "results": "Resultaten",
            "todaysGoal": "DOEL VANDAAG",
            "thisWeek": "Deze week",
            "points": "Punten",
            "workouts": "Trainingen",
            "scans": "Scans",
        ],

        "Polish": [
            "getStarted": "Zacznij",
            "continue": "Kontynuuj",
            "next": "Dalej",
            "save": "Zapisz",
            "cancel": "Anuluj",
            "done": "Gotowe",
            "logIn": "Zaloguj się",
            "logOut": "Wyloguj się",
            "scan": "Skan",
            "plan": "Plan",
            "compete": "Rywalizuj",
            "profile": "Profil",
            "ok": "OK",
            "whenWere": "Kiedy się",
            "youBorn": "urodziłeś?",
            "height": "WZROST",
            "weight": "WAGA",
            "referralCode": "Kod polecający",
            "settings": "Ustawienia",
            "notifications": "Powiadomienia",
            "darkMode": "Tryb ciemny",
            "language": "Język",
            "comingSoon": "Wkrótce",
            "comingSoonMessage": "Ta funkcja pojawi się wkrótce.",
            "latestScore": "Ostatni wynik",
            "results": "Wyniki",
            "todaysGoal": "CEL NA DZIŚ",
            "thisWeek": "Ten tydzień",
            "workouts": "Treningi",
            "scans": "Skany",
        ],

        "Swedish": [
            "getStarted": "Kom igång",
            "continue": "Fortsätt",
            "next": "Nästa",
            "save": "Spara",
            "cancel": "Avbryt",
            "done": "Klar",
            "logIn": "Logga in",
            "logOut": "Logga ut",
            "scan": "Skanna",
            "plan": "Plan",
            "compete": "Tävla",
            "profile": "Profil",
            "ok": "OK",
            "whenWere": "När",
            "youBorn": "föddes du?",
            "height": "LÄNGD",
            "weight": "VIKT",
            "referralCode": "Hänvisningskod",
            "settings": "Inställningar",
            "notifications": "Aviseringar",
            "darkMode": "Mörkt läge",
            "language": "Språk",
            "comingSoon": "Kommer snart",
            "comingSoonMessage": "Den här funktionen kommer snart.",
            "latestScore": "Senaste poäng",
            "results": "Resultat",
            "todaysGoal": "DAGENS MÅL",
            "thisWeek": "Denna vecka",
            "workouts": "Träningar",
            "scans": "Skanningar",
        ],

        "Romanian": [
            "getStarted": "Începe",
            "continue": "Continuă",
            "next": "Următorul",
            "save": "Salvează",
            "cancel": "Anulează",
            "done": "Gata",
            "logIn": "Conectare",
            "logOut": "Deconectare",
            "scan": "Scanare",
            "plan": "Plan",
            "compete": "Concurează",
            "profile": "Profil",
            "ok": "OK",
            "whenWere": "Când te-ai",
            "youBorn": "născut?",
            "height": "ÎNĂLȚIME",
            "weight": "GREUTATE",
            "referralCode": "Cod de referință",
            "settings": "Setări",
            "notifications": "Notificări",
            "darkMode": "Mod întunecat",
            "language": "Limbă",
            "comingSoon": "În curând",
            "comingSoonMessage": "Această funcție vine în curând.",
            "latestScore": "Ultimul scor",
            "results": "Rezultate",
            "thisWeek": "Săptămâna aceasta",
            "workouts": "Antrenamente",
            "scans": "Scanări",
        ],

        "Hebrew": [
            "getStarted": "התחל",
            "continue": "המשך",
            "next": "הבא",
            "save": "שמור",
            "cancel": "ביטול",
            "done": "סיום",
            "logIn": "התחברות",
            "logOut": "התנתקות",
            "scan": "סריקה",
            "plan": "תוכנית",
            "compete": "תחרות",
            "profile": "פרופיל",
            "ok": "אישור",
            "whenWere": "מתי",
            "youBorn": "נולדת?",
            "height": "גובה",
            "weight": "משקל",
            "referralCode": "קוד הפניה",
            "settings": "הגדרות",
            "notifications": "התראות",
            "darkMode": "מצב כהה",
            "language": "שפה",
            "comingSoon": "בקרוב",
            "comingSoonMessage": "תכונה זו תהיה זמינה בקרוב.",
            "latestScore": "ציון אחרון",
            "results": "תוצאות",
            "thisWeek": "השבוע",
            "workouts": "אימונים",
            "scans": "סריקות",
        ],
    ]
}
